test/attestation/identity/test_identity.py
test/attestation/trustchain/test_community.py
test/attestation/wallet/test_attestation_community.py
test/messaging/anonymization/test_community.py
test/messaging/anonymization/test_hiddenservices.py
test/peerdiscovery/deprecated/test_discovery.py
test/peerdiscovery/test_churn.py
test/peerdiscovery/test_edge_discovery.py
test/peerdiscovery/test_random_discovery.py
test/test_taskmanager.py
test/test_util.py
test/util.py

Nosetests on MacOS thinks it is a test when it's in the method name and then it fails.

Fixed twisted decorator names

---

ipv8/attestation/identity/community.py
ipv8/attestation/trustchain/block.py
ipv8/attestation/trustchain/caches.py
ipv8/attestation/trustchain/community.py
ipv8/attestation/trustchain/payload.py
test/attestation/trustchain/test_community.py

Added a dedicated message for a crawler response and each crawl now has an identifier. In addition, we also keep track of outstanding crawl requests in a request cache.
Also added block pair messages and added support for broadcasts of blocks.

Improved TrustChain crawler

---

README.md

After removing the `libnacl` submodule, the top note in `README.md` is no longer necessary.

Updated README after removing submodule

---

ipv8/messaging/anonymization/community.py
ipv8/messaging/anonymization/hidden_services.py
ipv8/messaging/anonymization/tunnel.py
test/messaging/anonymization/test_community.py

In this PR, I've added an optional delay when removing/destroying circuits, relays and exit sockets. This allows some post-mortem data to flow over the circuit, like payout messages in Tribler.
I've also addressed mid encoding in the `Tunnel` object. The way we encode it is a common source of errors. We now always store the mid in binary. We should eventually fix it to store a `Peer` object instead but requires takes a bit more work.

Added delay when removing tunnel info, fixed mid encoding

---

ipv8_service.py
twisted/plugins/ipv8_plugin.py

This causes an IPv8 instance to be loaded every time the module is imported.

Do not load IPv8 until the plugin is started

---

.gitignore
ipv8/attestation/trustchain/caches.py
ipv8/attestation/trustchain/community.py
ipv8/messaging/serialization.py
test/attestation/trustchain/test_community.py

In this PR, I improve the crawling mechanism in TrustChain. The most important change is that I send a dummy block back when receiving a crawl request and when there are no blocks to send to the request initiator. This avoids that the initiator should wait until the crawl request cache times out.
I've also added a test for crawling block pairs.

Improved crawling in the TrustChain community

---

ipv8/attestation/trustchain/caches.py
ipv8/attestation/trustchain/community.py

Also added a check to see whether the cache still exists when a crawl response is received (the timeout could have been triggered already which removes this cache).

Increased timeout of crawl request cache

---

ipv8/attestation/trustchain/database.py

After my experiment didn't work as expected, I ran a profiler and found out that the validation method of Trustchain blocks is _very_ expensive (often taking 100+ ms). The main reason for this behavior is the duration of database lookups, which is performed often when validating a block (i.e. fetching previous blocks or linked blocks).
A regular lookup in a sqlite database takes `O(n)` time where n is the number of rows in the database. Considering `SELECT` queries that span multiple columns (for instance, when fetching the linked block), this becomes expensive. By adding indices to the relevant, we are able to improve query speeds, to `O(log n)`. By doing so, it gives the expected results in my experiments and significantly reduced CPU usage, at the cost of some storage. This also makes …

READY: Supercharged Trustchain database queries by adding indices to columns

---

ipv8/attestation/trustchain/community.py
ipv8/attestation/trustchain/database.py
ipv8/deprecated/community.py
ipv8/messaging/anonymization/community.py
ipv8/overlay.py
test/attestation/trustchain/test_community.py

Now that the Trustchain database is faster, I re-implemented the live edges walker in IPv8. This is the basic implementation as initially designed by @qstokkink.

Re-implemented live edges

---

ipv8/messaging/anonymization/community.py
test/messaging/anonymization/test_community.py

In this PR, I made a few changes:
- add a separate method that returns a Deferred that callbacks with true or false. It indicates whether we should join a circuit or not. Developers can override this method and define their own logic there. In the case of Tribler, users with a low bandwidth token balance are rejected service.
- fixed a bug with the propagation of the destroy message in the tunnel community.
- added a few tests for destroying circuits

Added method to determine whether we should join a circuit, improved tunnel destroy mechanism and added tests

---

twisted/plugins/ipv8_plugin.py

Fixes the following Android runtime error:
```
04-18 10:59:14.572 4779-4818/? I/IPV8Service: Traceback (most recent call last):
04-18 10:59:14.572 4779-4818/? I/IPV8Service:   File "ipv8.py", line 31, in <module>
04-18 10:59:14.572 4779-4818/? I/IPV8Service:     IPV8Service().run()
04-18 10:59:14.572 4779-4818/? I/IPV8Service:   File "ipv8.py", line 21, in run
04-18 10:59:14.572 4779-4818/? I/IPV8Service:     from twisted.plugins.ipv8_plugin import Options, service_maker
04-18 10:59:14.572 4779-4818/? I/IPV8Service:   File "/data/user/0/org.internetofmoney.android/files/lib/python2.7/site-packages/twisted/plugins/ipv8_plugin.py", line 15, in <module>
04-18 10:59:14.572 4779-4818/? I/IPV8Service:     from ipv8_service import IPv8
04-18 10:59:14.572 4779-4818/? I/IPV8Service: ImportError: …
```

Fixed Twisted plugin import path for Android

---

ipv8/attestation/wallet/primitives/cryptosystem/boneh.py
ipv8/test/attestation/wallet/primitives/cryptosystem/test_boneh.py
requirements.txt

Fixes #106 
This sets the default prime size to 128 bit, this leads to 256 bit EC keys (which is still 4 times larger than the curve25519 keys we use for TrustChain).
And we only use this for a 2 bit message space 🤓

Added support for smaller prime generation

---

ipv8/attestation/wallet/community.py
ipv8/test/attestation/wallet/test_attestation_community.py
ipv8/test/base.py

Fixes #117 
- Fixes loading keys from database
- Fixes incorrect number of arguments for default completion callback
- Adds Windows-safe temporary directory creation method

READY: Fix bugs with loading AttestationCommunity

---

ipv8/REST/attestation_endpoint.py

Otherwise the REST caller needs the `mid` of itself (which is conveniently hidden right now).

Added convenience REST call for your own attributes

---

ipv8/messaging/interfaces/endpoint.py
ipv8/messaging/interfaces/udp/endpoint.py
ipv8/overlay.py
ipv8/test/mocking/exit_socket.py
ipv8/test/mocking/ipv8.py

Greatly speed-ups everything!
See  Tribler/tribler#2548

Reimplement UDP endpoint listener with Twisted DatagramProtocol

---

ipv8/configuration.py
ipv8_service.py

This adds the option in IPv8 to explicitly set listening address (e.g. network interface). By default it is `0.0.0.0`, meaning that it would listen to all interfaces.
It is important to note that it is impossible to send packets to real interfaces, if you set it to `127.0.0.1`. The thing would spit "wrong address" type of errors if you try to. So, it is useful for setting up isolated testnets (that was the reason to do this), and for better control on multi-hosted machines.
The patch with command-line option for overriding bootstrap servers in Tribler will follow as soon as this would become merged.

Add endpoint listening address option

---

ipv8/test/attestation/trustchain/test_community.py
ipv8/test/base.py

Fixes #135
Instead of sleeping a fixed amount of time, we deliver messages. This apparently was causing the (slower) test machine to rarely fail.
I also had to fix a test which depended on the old implementation (involving racing the block broadcasting).

Fixed introduce_nodes test method

---

ipv8/messaging/anonymization/community.py

This issue occurs when we have more circuits than we actually need, which can happen just after removing a download. The logging statement would then report that we need a negative amount of circuits, which is slightly confusing.

Fixed negative number of circuits needed

---

ipv8/REST/attestation_endpoint.py

This fixes leftover attestation requests from before the id wipe.

Fixed pending attestation request from previous id on clear

---

ipv8/messaging/interfaces/udp/endpoint.py
ipv8/test/messaging/interfaces/udp/test_endpoint.py

This PR implements a basic message send retry mechanism. This is necessary since we do not catch any `socket.error`, in contrast to Dispersy and the pre-UDP endpoint code. It fixes various socket-related errors we observed in Tribler.
I also noticed that there are no tests for the UDP endpoint so I've written a bunch of them. These tests also cover the retry mechanism I've made.

Implemented basic retry mechanism in UDP endpoint

---

create_test_coverage_report.py

This PR reinstates the pre-refactor coverage folders. This excludes the main entry point and the test folder.

Remove test folder from coverage report

---

ipv8/attestation/trustchain/community.py

Fixes #160 
- It is very easy to follow #160 and verify that this fixes the chain validation desync.
- I tried my best dirty Python and I could not turn it into a reliable unit test. If anyone thinks they can do it: I challenge you to write a unit test for this.

Fixed blockchain validation desync on packet reorder

---

ipv8/keyvault/__init__.py
ipv8/keyvault/private/m2crypto.py
ipv8/keyvault/public/m2crypto.py

Newer versions of python cryptography give a deprecation warning when you use the old `verifier()` and `signer()` methods.
This PR also allows for older cryptography versions to still function (although you probably shouldn't run those).
P.S. For anyone seeing the `InvalidSignature` for the first time: https://cryptography.io/en/latest/changelog/#v1-9

Added support for newer versions of cryptography

---

README.md
doc/trustchain.md
ipv8/attestation/identity/community.py
ipv8/attestation/trustchain/block.py
ipv8/attestation/trustchain/community.py
ipv8/attestation/trustchain/database.py
ipv8/attestation/trustchain/listener.py
ipv8/attestation/trustchain/payload.py
ipv8/test/attestation/trustchain/test_block.py
ipv8/test/attestation/trustchain/test_community.py
ipv8/test/mocking/ipv8.py

In this PR, I refactored the TrustChain overlay so it's a generic ledger that is reusable across several domains. The most important change is that each transaction now should have a type (i.e. `ask`, `tribler_bandwidth`, `attestation` etc). This transaction type is also stored in the database as a separate column for easy lookups. For instance, this allows us to get all blocks with an `attestation` transaction.
In addition, I also added a timestamp to each TrustChain record. These changes are included in this PR since it also breaks backward compatibility so I guess it's ok to combine it with the other breaking change (merging all chains together).

Refactored TrustChain so it's a single ledger now

---

ipv8/attestation/trustchain/community.py
ipv8/attestation/trustchain/database.py
ipv8/test/attestation/trustchain/test_community.py

This PR updates the TrustChain community so an incoming block is cast to its appropriate type, as specified by the block listeners. Right now, we always create a `TrustChainBlock` object.

Basing block type on BLOCK_CLASS variable

---

stresstest/endpoint_stresstest.py
stresstest/endpoint_stresstest_plot.R

As `bbq` is faster than my laptop, it requires a stricter variance to check for slowdown.

Endpoint stresstest properly exits

---

ipv8/peer.py

Right now, we recalculate the public key and the mid every time we require them from a `Peer` object. As `Peer` objects have static keys anyway, this makes no sense and we can save ourselves some CPU cycles.

Optimized Peer mid and public_key calls

---

ipv8/test/mocking/community.py
ipv8/test/mocking/endpoint.py

Fixes  #192
This PR fixes two obscure errors in the tests, both having to do with address resolution:
1. Sometimes a Community will not have had any chance to estimate its own wan address and will therefore try to use the machine's estimated lan address. This can throw off the tests which assume a stable ip.
2. The generated addresses by `AutoMockEndpoint` may be flagged (false positive) as lan addresses as the actual machine's address is not part of the fake internet layer provided by the mocked endpoints.

Fixed AutoMockEndpoint picking illegal addresses

---

ipv8/peer.py

Fixes #194 .
Before, a Peer's `__hash__()` was mutable through changes in the address. With this PR the hash is based on only the mid of a Peer, which is immutable (as it should be).

Fixed mutable Peer __hash__()

---

ipv8/attestation/trustchain/community.py

Otherwise, both the mainnet and testnet identity will use the same database, which will lead to conflicts, double spend and other complications.

Using seperate database when on TrustChain testnet

---

ipv8/REST/attestation_endpoint.py

The existing whitewashing attack was not good enough: Trustchain detected it as double spending. It turns out we need an entirely new key to subvert the detection mechanism. Good for Trustchain, bad for the attacker.

Use new key in whitewashing attack

---

ipv8/dht/community.py
ipv8/test/base.py
ipv8/test/mocking/ipv8.py

Similar to how a TrustChain community can be side-loaded during the tests.

Optionally load a DHT community in tests

---

ipv8/attestation/trustchain/community.py

We assumed that we are always sending blocks in our own chain when responding to a crawl request. However, the new IPv8 crawler can request blocks that are not in your chain. This check was not consistent with that notion, which results in many missing blocks for the crawler (since they were simply not being sent).

Changed validation rule when sending crawl resp.

---

ipv8/attestation/trustchain/community.py
ipv8/attestation/wallet/community.py
ipv8/deprecated/community.py
ipv8/deprecated/lazy_community.py
ipv8/dht/community.py
ipv8/dht/discovery.py
ipv8/messaging/anonymization/community.py
ipv8/messaging/anonymization/hidden_services.py
ipv8/peerdiscovery/deprecated/discovery.py
ipv8/test/dht/test_discovery.py

Removed the calls to the `_ez_unpack_*` methods, and added calls to the `lazy_wrapper` decorators in lieu. Also refactored the deprecated/community.py module in order to move the `lazy_wrapper` decorators and the `EZPackOverlay` class to a new module:  deprecated/lazy_community.py.

Deprecated _ez_unpack_* function calls swap with  lazy_wrapper decorators

---

ipv8/attestation/trustchain/community.py
ipv8/deprecated/community.py

Changed the decorator from `@lazy_wrapper` to `@lazy_wrapper_wd` for the `on_introduction_response method` method in both the `TrustChainCommunity` and `Community` classes. Noticed the need for this change when rebasing the #233 PR branch onto the **upstream/master**, as `@lazy_wrapper`'s inner method `wrapper` would throw an error which flagged that too many parameters were passed (4 instead of 3). It should be mentioned that the REST API and the tests were working normally (and were passing), but errors were thrown. The disadvantage of this change is that Pylint errors are introduced, and the data gets unpacked twice. The advantage is that errors are not thrown any longer.

Small ammendment to decoration of on_introduction_response method

---

ipv8/taskmanager.py
ipv8/test/test_taskmanager.py

Fix for https://github.com/Tribler/py-ipv8/issues/253
Raises an error in case of duplicate name and replaces the task with the new one.
The shutdown check is moved to be the 1st one to prevent replacing tasks before the shutdown.

Fix adding task with duplicate name to taskmanager

---

ipv8/test/base.py

It is safer to generate dir names in this way. It is important if we want to run tests simultaneously.

Refactor TestBase.temporary_directory for parallel execution safety

---

run_all_tests_trial.py

This one slipped through the cracks after review (https://github.com/Tribler/py-ipv8/pull/266#discussion_r217725452).

Use join() for path building in test runner

---

ipv8/attestation/trustchain/listener.py
ipv8/database.py
ipv8/keyvault/keys.py
ipv8/messaging/interfaces/endpoint.py
ipv8/messaging/serialization.py
ipv8/overlay.py
ipv8/peerdiscovery/discovery.py
requirements.txt

Related to #265. Python 3 requires a different meta class definition style: https://portingguide.readthedocs.io/en/latest/classes.html#metaclasses
This PR switches all metaclass definitions to the `six` Python 2/3 compatible format. Note that we will require six as an "additional" dependency (this is already used by `cryptography` so we don't need to install anything new on our machines).

Switched to Python 3 compatible meta classes

---

ipv8/attestation/trustchain/block.py
ipv8/attestation/trustchain/caches.py
ipv8/attestation/trustchain/community.py
ipv8/attestation/trustchain/database.py
ipv8/attestation/trustchain/payload.py
ipv8/attestation/trustchain/settings.py
ipv8/test/attestation/trustchain/test_block.py
ipv8/test/attestation/trustchain/test_community.py

In this PR, I made quite a few changes to the TrustChain code and protocol. It includes:
- A fix for the block broadcast mechanism, where each block was unintentionally pushed to 1110 users. When this PR is merged, it is pushed to _only_ 25 users.
- An extension of the introduction request/response, where information about the length of ones chain is included (sequence number of their latest block).
- A separate file to store various important TrustChain settings. This includes settings for the block validation ranges (how many blocks do I need prior to signing one) and maximum number of blocks in the database.
- Made the database upgrade script idempotent.
- A database pruning loop that removes old blocks when the database grows too big.
- Made the crawler less aggressive when we already …

Various improvements to TrustChain

---

ipv8/attestation/trustchain/community.py
ipv8/messaging/anonymization/community.py

The `extra_bytes` field in the payload is not always set, i.e. when being introduced by someone else through the IPv8 crawler.

Fixed TrustChain introductions

---

ipv8/messaging/deprecated/encoding.py
ipv8/messaging/deprecated/sorting.py
ipv8/test/messaging/deprecated/test_encoding.py
ipv8/test/messaging/deprecated/test_sorting.py
test_classes_list.txt

This is a platform agnostic sorting method for mixed-type datastructures, this allows us to port to other languages like Java (or even Python 3).
Fixes #295. Requires a hard reset of the TrustChain database.

Added custom sorting method for encoding

---

ipv8/test/mocking/ipv8.py

There are various overlays which are dependent on the TrustChain when shutting down (i.e. the tunnel community).

Fixed order of unloading

---

stresstest/peer_discovery.py

This tool measures the time it takes for peers to find each other in a random overlay with a random port.
It returns the comma separated time until each peer sees the other peer as verified (the difference is the time until the `IntroductionResponse` has been received).
```
$ python peer_discovery.py 
1.5171,1.6084
$ python peer_discovery.py 
4.1069,4.1078
$ python peer_discovery.py 
1.1072,1.1080
$ python peer_discovery.py 
1.6127,1.6137
$ python peer_discovery.py 
1.1069,1.1082
$ python peer_discovery.py 
2.0182,2.1097
$ python peer_discovery.py 
1.1071,1.1076
$ python peer_discovery.py 
4.0171,4.1093
$ python peer_discovery.py 
3.5177,3.6088
$ python peer_discovery.py 
12.0163,12.1080
```
We can use this to create a continuous job on Jenkins, measuring the health of the tracker. Note …

Added peer discovery latency tool

---

stresstest/peer_discovery.py

Right now the same peer will always report twice, so after 0.1 seconds we would always report to have gotten the introduction response.
This PR makes sure it is really the other peer reporting that it has found a peer.

Fixed same peer returning low and high edge discovery

---

ipv8/REST/attestation_endpoint.py
ipv8/REST/rest_manager.py
ipv8/attestation/wallet/community.py
ipv8/test/attestation/wallet/test_attestation_community.py
ipv8/util.py

This PR fixes the IdentityCommunity receiving 50/50 unicode and byte string attribute values due to the `json` library. Everything is now a byte string again.
This PR also fixes `cast_to_unicode` performing `str()` on a `bytes` object, which causes the following:
```python
>>> str(b'a')
"b'a'"
```
Instead this PR uses the following function for `bytes` in `cast_to_unicode`:
```python
>>> f = lambda x: "".join([chr(c) for c in x])
>>> f(b'a')
'a'
```

Fixed Python3 JSON only handling and returning unicode

---

ipv8/attestation/trustchain/block.py
ipv8/attestation/trustchain/community.py
ipv8/attestation/trustchain/database.py
ipv8/test/attestation/trustchain/test_community.py

In this PR, I fixed two errors related to source/link blocks:
- fixed the block type of a linked block. Without the proper logic, the provided `block_type` parameter when creating a linked block would be ignored.
- fixed the validation mechanism when creating multiple linked blocks for a single source block. This was classified as a double-spend attempt.

Fixed two errors with source/link blocks

---

ipv8/peer.py
ipv8/test/test_peer.py
twisted/plugins/tracker_plugin.py

Every 30 seconds we throw out peers who have not reached us in the past 2 minutes.
The expected amount of contacts to this specific tracker should be `1.7`.

Simplified tracker plugin

---

ipv8/community.py

This PR updates the list of bootstrap trackers for IPv8 and Dispersy.
Few things to note:
- All trackers running in port [6420+x] are Dispersy trackers. When Dispersy is out, we'll remove them.
- All other trackers running in port [6520+X] are IPv8 trackers. 
- DNS name for Dispersy and IPv8 trackers follows the respective domain name tribler.org and ip-v8.org

New bootstrap servers

---

.pylintrc
create_test_coverage_report.py
ipv8/attestation/trustchain/block.py
ipv8/attestation/trustchain/community.py
ipv8/attestation/trustchain/database.py
ipv8/database.py
ipv8/dht/discovery.py
ipv8/messaging/anonymization/hidden_services.py
ipv8/messaging/anonymization/tunnelcrypto.py
ipv8/messaging/bloomfilter.py
ipv8/messaging/deprecated/encoding.py
ipv8/messaging/deprecated/sorting.py
ipv8/messaging/interfaces/udp/endpoint.py
ipv8/peerdiscovery/network.py
ipv8/requestcache.py
ipv8/test/attestation/trustchain/test_community.py
ipv8/test/messaging/interfaces/udp/test_endpoint.py
ipv8/test/messaging/test_bloomfilter.py
ipv8/test/mocking/rest/base.py
ipv8/test/mocking/rest/rest_peer_communication.py
ipv8/test/test_taskmanager.py
ipv8/util.py
stresstest/endpoint_stresstest.py

Fixes #382, I don't think we can move anything else to `six`.
The following `six` functionality is now used:
- `StringIO`
- `Queue`
- `urllib`/`urlparse`
- `xrange` (formerly`grange`)
- `isinstance( ... , integer_types)` (formerly `is_long_or_int`)
- `isinstance( ... , text_type)` (formerly `is_unicode`)

Moved as many classes to six as possible

---

ipv8/messaging/serialization.py

This, ahem, adds double precision float to our serializer. Necessary for GigaChannels.

Add double type to serializer

---

ipv8/lazy_community.py
ipv8/messaging/serialization.py
ipv8/test/messaging/test_serialization.py

By popular demand and because I am a crow pleaser: slightly smaller pack and unpack methods for Serializable instances.
Adds:
- `Serializer.ez_pack_serializables` which takes a list of `Serializable` objects instead of having to concatenate any lists or outputs yourself.
- `Serializer.ez_unpack_serializables` which throws an exception if there is remaining data instead of forwarding the remaining data. This avoids some duplicate code we saw in the wrappers.

Added ez (un)pack methods to Serializer

---

ipv8/attestation/trustchain/database.py

The remove_old_blocks call in the database would delete blocks that are linked to a peers own chain. If this happens, the peer can't present full blocks of his past transactions.

Don't delete blocks that are vital to your own chain

---

ipv8/attestation/trustchain/community.py

We changed the Trustchain community id but forgot to update the testnet identifier.

Updated TrustChain testnet community id

---

ipv8/database.py
ipv8/util.py

Follows the Python porting best practice [___use feature detection instead of version detection___](https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection).
Also:
* __cast_to_long(3.2)__ should return a non-floatingpoint result in both Python 2 and Python 3
* __python2 -c "import sys ; print(sys.maxsize == sys.maxint)"__  # True
[flake8](http://flake8.pycqa.org) testing of https://github.com/Tribler/py-ipv8 on Python 3.7.1
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./ipv8/util.py:23:30: F821 undefined name 'long'
cast_to_long = lambda x: long(x)
^
./ipv8/util.py:24:33: F821 undefined name 'unicode'
cast_to_unicode = lambda x: unicode(x)
^
./ipv8/database.py:46:21: F821 undefined name 'buffer' …
```

Use feature detection instead of version detection

---

ipv8/peerdiscovery/discovery.py
ipv8/test/peerdiscovery/test_edge_discovery.py

Previously the edge walk would use (possibly overridden and biased) neighborhood selection.

Sanitized edge walk neighborhood selection

---

ipv8/peerdiscovery/community.py

We forgot to add the `max_peers` code to the DiscoveryCommunity.

Add forgottren max_peers to DiscoveryCommunity

---

ipv8/attestation/trustchain/community.py
ipv8/community.py
ipv8/peerdiscovery/community.py
ipv8/peerdiscovery/discovery.py
ipv8/test/peerdiscovery/test_community.py
stresstest/peer_discovery_defaults.py

Fixes #427 
This allows us to spot regressions in the peer discovery logic of full-blown Communities.
Note that this is quite a bit heavier than `peer_discovery.py` and loads the entire stack.

Added default config Community intro stresstest

---

ipv8/community.py
ipv8/dht/community.py
ipv8/messaging/anonymization/community.py
ipv8/peerdiscovery/discovery.py
ipv8/test/peerdiscovery/test_edge_discovery.py
ipv8/test/peerdiscovery/test_random_discovery.py

- Only depend on `add_verified_peer` from intro requests and responses (our tests didn't like this)
- Don't add verified peers on TunnelCommunity extends

Fix potential peer leaks

---

ipv8/messaging/lazy_payload.py
ipv8/messaging/payload.py
ipv8/test/messaging/test_lazy_payload.py
test_classes_list.txt

After lessons learned from #388, this is the second attempt to make Payload definitions smaller.
Some examples (also [check out the unit tests for other examples](https://github.com/Tribler/py-ipv8/pull/441/files#diff-c3b5edee13f972a762a9728a27cf9de0R10)):
```python
class A(VariablePayload):
format_list = ['I', 'H']
names = ["a", "b"]
class B(VariablePayload):
format_list = ['4SH']
names = ["address"]
def fix_pack_address(value):
return (socket.inet_aton(value[0]), value[1])
def fix_unpack_address(value):
return (socket.inet_ntoa(value[0]), value[1])
a = A(1, 2)
print(a.b) # 2
b = B(("1.1.1.1", 0))
print(b.address) # ("1.1.1.1", 0)
```

Added VariablePayload

---

ipv8/REST/rest_manager.py

The CORS header is needed in the response of the REST API for the browser to accept API responses

Added CORS header

---

ipv8/messaging/serialization.py
ipv8/test/messaging/test_serialization.py

Now that the `Serializable` no longer supports list descriptors, we can also remove `unpack_multiple_as_list`.

Removed unpack_multiple_as_list

---

ipv8/REST/overlays_endpoint.py
twisted/plugins/ipv8_plugin.py

With this, we could remove the `/statistics/overlays` endpoint in Tribler and use `/ipv8/overlays` instead 👍

Added statistics to IPv8 overlay endpoint

---

ipv8/database.py

Solves the following bug for calls with `get_lastrowid=True`:
```python
File "/home/quinten/Documents/py-ipv8/ipv8/database.py", line 54, in wrapper
return f(self, *args, **kwargs)
File "/home/quinten/Documents/py-ipv8/ipv8/database.py", line 319, in execute
return _thread_safe_result_it(result, fetch_all)
File "/home/quinten/Documents/py-ipv8/ipv8/database.py", line 60, in _thread_safe_result_it
rows = (result.fetchall() if fetch_all else result.fetchone()) or []
AttributeError: 'int' object has no attribute 'fetchall'
```

Fixed database trying to cursor wrap an int

---

ipv8/attestation/trustchain/database.py
ipv8/test/attestation/trustchain/test_database.py
test_classes_list.txt

Added an option to fetch the connected peers to a public key (user). It is added to build a beautiful trust graph in Tribler.
Instead of this (expensive)
Only show connected peers (cheaper)

Return connected peers

---

ipv8/attestation/trustchain/database.py

You can now pass a list of block types instead of a single block type. This will help us if we want to query the latest blocks in a specific chain for some application that only uses a limited number of different block types.

Changed get_latest_blocks behaviour

---

ipv8/REST/attestation_endpoint.py
ipv8/REST/base_endpoint.py
ipv8/REST/dht_endpoint.py
ipv8/REST/json_util.py
ipv8/REST/network_endpoint.py
ipv8/REST/overlays_endpoint.py
ipv8/REST/rest_manager.py
ipv8/REST/trustchain_endpoint.py
ipv8/REST/tunnel_endpoint.py
ipv8/test/REST/attestationendpoint/test_attestation_endpoint.py

In this commit, I copied the json_util.py file over from Tribler. These methods are used in the IPv8 REST API to encode to/from JSON, in a Python 3-compatible way. I also fixed a few inconsistencies and code style errors.

Properly encoding to/from JSON in Python 3

---

ipv8/attestation/wallet/caches.py

Fixes #513
This bumps up the time you have to allow verification of an attribute to two minutes (previously 10 seconds).
Note: We do not bump this up to two minutes for all HashCaches as suggested in #513, as this would also include the pending challenge-response pairs.

Allocated more time for allow verify

---

ipv8/attestation/trustchain/database.py
ipv8/test/attestation/trustchain/test_community.py

Also changed the crawl test so it's testing the get_latest_blocks. This is not a durable solution and we should have a seperate test suite to test the TrustChain database logic.

Fixed unicode binding (it is now bytes)

---

ipv8/attestation/trustchain/block.py

Fixes #526.
Made the TrustChain blocks unicode safe.

Fixed TrustChain block unicode strings

---

setup.py

Suggested release message
---
Tag version: 1.8
Release title: IPv8 v1.8.1033 release
Body:
Includes the first 1033 commits (+139 since v1.7) for IPv8, containing:
- Return connected peers
- Update hidden services
- Added endpoint adapter for pex communities
- Introduce peer_flags + encrypt message_id
- Retry mechanism for new TC block publishing to DHT
- Tunnel fixes
- Converted implements to implementer
- Writing key file in binary mode
- Reading key file in binary mode
- removed bloom filter code
- Allow anonymous communities
- Made Attestation/Identity communities anonymous
- Fix for anonymizing DiscoveryCommunity
- Changed get_latest_blocks behaviour
- Removed netifaces requirement
- Extract libsodium installation tutorial and add it to README.md
- Let anonymous communities only …

Automated Version Update

---

ipv8/attestation/trustchain/community.py
ipv8/attestation/trustchain/settings.py
ipv8/test/attestation/trustchain/test_community.py

This allows us to disable broadcasts for specific block types.

Added option to disable broadcast for specific blocks

---

ipv8/attestation/wallet/bonehexact/attestation.py
ipv8/test/attestation/wallet/test_attestation_community.py

The old calculation method failed with 0 component vectors (https://github.com/Tribler/tribler/issues/4461#issuecomment-516798549)

Fix boneh exact 0-vector certainty calculation

---

ipv8/messaging/anonymization/payload.py
ipv8/util.py

In this PR, I propose to copy the `ensure_str`, `ensure_binary` and `ensure_text` methods from the six 1.12 source code. By doing so, we are not dependant anymore on six 1.12, which apparently is not propagated sufficiently yet in all package managers. I don't consider this a permanent solution but at least until we get our dependencies in Tribler in order (e.g., `cherrypy`), I think it is the best we can do.

Copied ensure_* methods from six 1.12

---

ipv8/community.py

This PR allows peers to connect to each other if the tracker is running on the same subnet. This is particularly useful for the DAS-5 experiments.

Fixed tracker on same subnet connectability

---

ipv8/REST/dht_endpoint.py
ipv8/dht/community.py
ipv8/dht/payload.py
ipv8/dht/storage.py
ipv8/test/REST/dht/test_dht_endpoint.py

This PR attempts to address one of the improvements to the DHT flagged in issue #451. Added support for block entries in the DHT, whose chunks do not fit into a single response returned after a DHT block request. The implementation forwarded in this PR is able to return a block which is complete and has the maximal version, as long as it is within the scope of the query. The following high level description of the algorithm should hopefully make what this means more clear (*chunk* and *block* are interchangeably used):
1. Given the public key of a peer, forward a REST request via HTTP for the peer's latest block. 
1. The peer which receives this request will query its own DHT object for the entries under a special key for which the target peer's TC blocks are stored. Set `query_start = …

Support for large block retrieval in DHTs 

---

ipv8/test/REST/attestationendpoint/test_attestation_endpoint.py
ipv8/test/REST/dht/test_dht_endpoint.py
ipv8/test/base.py
ipv8/test/mocking/rest/base.py
ipv8/test/mocking/rest/ipv8.py
ipv8/test/mocking/rest/peer_interactive_behavior.py
ipv8/test/mocking/rest/rest_api_peer.py

Fixes #583
Additionally:
- Avoids using the wild bootstrap servers.
- Uses `TestBase` for unit test management to avoid leaking tests and removing duplicate code.

Fix REST test teardown

---

ipv8/attestation/wallet/community.py
ipv8/test/attestation/wallet/test_attestation_community.py

Fixes #534
- The attestation request caches are now not only linked to the attester id, but also to the (logical) timestamp of the request.
- Also fixed `irmaexact` algorithm not being available to the community.

Added multiple attestation requesting

---

ipv8/attestation/trustchain/block.py
ipv8/test/attestation/trustchain/test_block.py

`decode` returns the current stream offset and the decoded object, we were sending both instead of just the output.

Fixed trustchain block iter returning offset

---

ipv8/attestation/trustchain/community.py
ipv8/attestation/trustchain/settings.py

For experiments, we might want to increase this number. By default, it is still 10 but during an experiment, we can increase this number to allow for larger crawl batches.

Made max crawl batch a setting

---

ipv8/attestation/trustchain/community.py

When working on the Noodle protocol, we noticed that if the duration between invocation of the addCallback(..., on_should_sign_outcome) method and calling the on_should_sign_outcome method is long, and process_half_block is invoked again in the meantime, the variables used by the on_should_sign_outcome method are incorrect. Instead, we should immediately bind the blk, peer and validation variables, which is what this PR proposes. Furthermore, I extracted the on_should_sign method from the process_half_block method, which makes the process_half_block method more readable.

Binding on_should_sign_outcome lambda variables at runtime

---

ipv8/messaging/anonymization/tunnelcrypto.py

Fixes https://github.com/Tribler/py-ipv8/issues/632. Sister PR of https://github.com/Tribler/py-ipv8/pull/636.

Make TunnelCrypto compatible with libnacl 1.7

---

scripts/__scriptpath__.py
scripts/exitnode_ipv8_only_plugin.py
scripts/ipv8_plugin.py
scripts/tracker_plugin.py
scripts/trustchain_crawler_plugin.py
stresstest/__scriptpath__.py
stresstest/bootstrap_rtt.py
stresstest/endpoint_stresstest.py
stresstest/peer_discovery.py
stresstest/peer_discovery_defaults.py

Instead of modifying system path on a per-module basis it is instead modified in a __scriptpath__.py file that is imported into the desired module.
In addition instead of appending into the system path the modification inserts into it to prevent path overrides.
Fixes #642

Unite system path modifications as __scriptpath__.py files

---

ipv8/peer.py
ipv8/test/test_peer.py

In Python 2.7, there is a slightly different behaviour of the not equal operation (!=) compared to Python 3. In particular, in Python 2.7, statements like peerA == peerB would evaluate to True but statements like peerA != peerB would not evaluate to False, due to the absence of a __ne__ method in the Peer class. This PR fixes this issue and modifies an existing test to test this change.

Fixed peer inequality check in Python 2.7

---

ipv8/attestation/trustchain/block.py
ipv8/util.py

Replace lambdas with functions. Remove a use of `old_round` (total removal depends on Tribler/tribler#5024 and Tribler/anydex-core#31). ~~Other minor refractoring: removing the redundant `u` prefix from strings; remove cast_to_* functions when it is immediately clear how to manipulate the data.~~
Fixes #651.

Replace lambdas with functions

---

ipv8/peerdiscovery/discovery.py

Currently, the `RandomWalk` discovery strategy tries to send an introduction request to a random verified peer in each step, not considering if the requested community is actually supported by that peer. This PR introduces filtering, so only peers that are members of the community are contacted.

Filter peers by community in RandomWalk strategy

---

scripts/tracker_plugin.py
systemd/ipv8-tracker@.service

It seems that with these changes, trackers with Python 3 and `asyncio` work correctly, at least they pass the Test_BootstrapServers job on Jenkins.
When this PR is merged, I will update the Ansible script and convert all bootstrap servers 👍

Fixed tracker systemd file + error in the script

---

ipv8/test/messaging/anonymization/test_datachecker.py
test_classes_list.txt

While I was debugging the libtorrent data checker, I wrote this basic test, so I thought I could as well add it to the IPv8 code base 👍 
Note that these tests only verify libtorrent DHT packets. We should probably also add some tests for UTP data later.

Added basic tests for the DataChecker class

---

ipv8/attestation/trustchain/community.py
ipv8/test/base.py

Currently, the block is being broadcasted to random peers in the network. This PR filters only peers participating in TrustChain community.
Additionally, service discovery was broken in tests due to a type error, which originally caused some tests to fail after this change.

Fix block broadcast in TrustChain

---

ipv8/attestation/trustchain/community.py
ipv8/test/attestation/trustchain/test_community.py

Currently, TTL is decremented by 2 whenever a block is received. This PR fixes it and adds a test that fails before this change.

Fix decrementing TTL when received block broadcast

---

scripts/tracker_plugin.py

Inactive peers are currently not being removed from the tracker due to a bug in `SimpleChurn` strategy. The churn task crashes when the first peer is removed. This results in very inefficient peer discovery and a memory leak.
```
Exception in callback TaskManager.register_task.<locals>.done_cb(<Task finishe...g iteration')>) at /Users/matt/Development/Projects/py-ipv8/ipv8/taskmanager.py:101
handle: <Handle TaskManager.register_task.<locals>.done_cb(<Task finishe...g iteration')>) at /Users/matt/Development/Projects/py-ipv8/ipv8/taskmanager.py:101>
Traceback (most recent call last):
File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File …
```

Fix removing inactive peers from tracker

---

ipv8/attestation/trustchain/block.py
ipv8/test/attestation/trustchain/test_block.py

The `is_genesis` condition in `update_block_invariant` prevented the sub-conditions to ever be evaluated true.
The tests were not failing only because the validation result was still invalid due to an invalid signature.

Fix TrustChain genesis block invariant validation

---

ipv8/attestation/trustchain/community.py
ipv8/attestation/trustchain/settings.py

Fixes #679 by using a set for broadcast lookups and an upper limit of 100,000 broadcasted block identifiers.

Used a set instead of list for relayed_broadcast

---

ipv8/community.py

Now we don't need the object to be a `Payload` subclass specifically.

Changed msg handler type check

---

ipv8/taskmanager.py

Leaving Tribler Core running over a night subscribed for 300 channels (constantly trying to download these, but unable to) shows a memory leak of about 40 Mb per hour. Printing memory usage stats regularly with `mem_top` package shows the leak is caused by `weakref`s for  `_asyncio.Task`s accumulating in a set. What probably happens is `_pending_tasks` keeping the references and not releasing them in some cases, such as timeouts, etc.
By making `TaskManager` use `WeakValueDictionary` the accumulation stops. `mem_top` shows no signs of `weakref` leak. Over the night, the total memory usage stabilises at 260Mb, that is only 120 Mb more than the starting RAM usage.

Fix memory leak in TaskManager by using weak references

---

ipv8/REST/attestation_endpoint.py

If the `id_metadata` argument is not given for the `/attestation` endpoint the default is now set to `['id_metadata']`. However, this causes a TypeError in https://github.com/Tribler/py-ipv8/blob/master/ipv8/attestation/wallet/community.py#L96 since a string is expected as key  to retreive the correct vale of the `FORMATS` list.
1. Follow the [Attestation Tutorial](https://py-ipv8.readthedocs.io/en/latest/basics/attestation_tutorial/#enrollment-attestation-flow) up to the first step, a POST to `/attestation`
2. Verify that the following error occures:
```
File "/home/niels/Documents/ipv8/pyipv8/ipv8/attestation/wallet/community.py", line 96, in get_id_algorithm
return ID_ALGORITHMS[FORMATS[id_format]["algorithm"]](id_format)
TypeError: unhashable type: 'list'
```
3. Apply the PR and …

Correct the fallback argument for 'id_metadata'

---

ipv8/attestation/wallet/community.py
ipv8/community.py
ipv8/messaging/anonymization/hidden_services.py
ipv8/messaging/anonymization/pex.py
ipv8/messaging/interfaces/endpoint.py
ipv8/test/mocking/endpoint.py

This prefers to use prefix mapping instead of always looping through all listeners.
Also fixed a bug where the `AttestationCommunity` had a module-level lock instead of an instance-level lock.

Used prefix mapping for endpoint

---

ipv8/attestation/trustchain/database.py
ipv8/database.py
ipv8/test/test_database.py

When running IPv8 with Python 2.7, it stored several text element as `TEXT` type. In Python 3, however, we are using `bytes` to fetch from the database, causing SQL queries to return incorrect results.
This PR bumps the version of the TrustChain database and converts all `TEXT` elements to the `BLOB` type. This should fix the SQL queries that are using `bytes` in their queries, and requires no changes to the existing SQL queries.

Fix sqlite text type

---

ipv8/test/mocking/ipv8.py

This is required for the REST API tests in AnyDex, that rely on this method in the MockIPv8 class.

Added get_overlay(s) method to MockIPv8

---

ipv8/REST/rest_manager.py

Currently the `port` for the REST API is configurable but the host is not. This causes issues when you like to bind the REST API to a specific interface or IP. For example, when using IPv8 inside a Docker container the host must be set to `0.0.0.0` in order to make communication possible. When bind to `127.0.0.1` (the current default) communication with the outside world is not possible.
This PR adds a seconds parameter `host` to the `start()` method of `rest_manager.py`. The default value is still `127.0.0.1`.

Make the host binding for the REST api configurable

---

ipv8/attestation/default_identity_formats.py
ipv8/attestation/identity/community.py
ipv8/attestation/identity_formats.py
ipv8/attestation/schema/manager.py
ipv8/attestation/wallet/bonehexact/algorithm.py
ipv8/attestation/wallet/community.py
ipv8/attestation/wallet/irmaexact/algorithm.py
ipv8/attestation/wallet/pengbaorange/algorithm.py
ipv8/test/attestation/wallet/irmaexact/test_algorithm.py
test_classes_list.txt

Related to #733.
This PR:
- Moves the default identity formats to the `default_identity_formats.py` file.
- Makes `IdentityAlgorithm` load formats from an argument instead of a global variable.
- Adds a `SchemaManager` to manage and lazy-load schemas and available algorithms.
- Refactors `AttestationCommunity` to use the `SchemaManager`.
- Adds missing IRMA test to `test_classes_list.txt`.
No changes were made to the protocol. This PR opens the way to load new schemas through the REST API.

Refactored id formats into SchemaManager

---

create_test_coverage_report.py
ipv8/test/messaging/interfaces/udp/test_endpoint.py
run_all_tests.py
setup.py

- Removes unused endpoint tests.
- Fixes #744.
- Added test requirements to `setup.py`.
- Added universal Python-based test invocation script (to remove operating specific `run_all_tests_*` scripts).
The new universal test script is also multiprocessed, which brings the test time down from 54 seconds to 18 seconds.
I will follow up with another PR for the `run_all_tests.py` script, integrating it properly into the documentation. First I want to do some preliminary field testing (if it turns out it doesn't work *everywhere*, I'll remove it again).

Various testing infrastructure improvements

---

ipv8/REST/health_endpoint.py
ipv8/REST/root_endpoint.py

Related to #752
This adds an Endpoint that stores the last 100 core tick drift measurements.
It can be enabled and disabled with a put request (it starts off disabled).

Added REST endpoint for measuring core drift

---

ipv8/attestation/identity/attestation.py
ipv8/attestation/identity/metadata.py
ipv8/attestation/signed_object.py
ipv8/attestation/tokenchain/chain.py
ipv8/attestation/tokenchain/token.py
ipv8/test/attestation/tokenchain/test_chain.py

This is the next step for #733. This PR adds two primitives (explicitly*) for identities:
- Metadata: a signed combination of a JSON dictionary and a pointer to a Token.
- Attestations; a signed pointer to Metadata.
As they are highly similar to the way Token objects are signed and serialized I extracted a common base class: the `AbstractSignedObject`.
This PR does not add any new logic - only data classes and moving code into an abstract class. This reduces clutter in following PRs.
*Formerly this was(/in the current implementation this is) inside of Trustchain implicitly.

Added identity datatypes

---

ipv8/REST/dht_endpoint.py
ipv8/REST/tunnel_endpoint.py
ipv8/dht/community.py
ipv8/dht/discovery.py
ipv8/dht/payload.py
ipv8/dht/provider.py
ipv8/dht/trie.py
ipv8/messaging/anonymization/community.py
ipv8/messaging/anonymization/hidden_services.py
ipv8/test/dht/test_discovery.py

This PR:
* Lowers the number of DHT lookups.
* Lowers the number of find-requests per lookup.
* Reduces the bandwidth usage of the DHT by ~50%, based on initial experiments within Tribler. As the network upgrades, bandwidth usage should go down further still.
* Adds a debug field to the DHT endpoint that allows some insight in the messages sent/received to do a certain lookup

Updated DHT to use less bandwidth

---

doc/basics/attestation_tutorial.rst
ipv8/REST/attestation_endpoint.py
ipv8/attestation/identity/community.py
ipv8/attestation/identity/database.py
ipv8/attestation/identity/manager.py
ipv8/attestation/identity/payload.py
ipv8/attestation/tokentree/tree.py
ipv8/test/REST/attestationendpoint/test_attestation_endpoint.py
ipv8/test/REST/rest_base.py
ipv8/test/attestation/identity/test_identity.py
ipv8/test/attestation/tokentree/test_tree.py

This PR performs integration of the new ID Trustchain derivative with the identity overlay for #733.
In the process of testing I also automated the tutorial (which I will probably make a PR for in the future):
https://gist.github.com/qstokkink/a76a91ec00f8e5c496e0d21c91af6217
Concretely this PR;
- Updates the attestation tutorial documentation.
- Ports the old REST API to use the new backend.
- Ports the old community to no longer subclass the currency Trustchain.
- Ports the old identity tests to the new format.
- Adds a convenience method to the ID 2.0 token datastructure for getting a single chain.
- Internally uses unicode strings instead of flip-flopping to and from bytes for metadata.
- Fixes race conditions in the REST tests.
*Roadmap*
This is the most intensive operation of #733, …

Integrated ID 2.0 pseudonym management

---

ipv8/REST/asyncio_endpoint.py
ipv8/dht/community.py
ipv8/messaging/anonymization/community.py
ipv8/messaging/lazy_payload.py
ipv8/requestcache.py
ipv8/taskmanager.py
ipv8/test/attestation/tokentree/test_tree.py
ipv8/test/dht/test_community.py
ipv8/test/test_taskmanager.py
ipv8/util.py

This PR fixes a deadlock that occurs if:
* The request cache is in the middle of shutting down, but still holds the lock.
* At the same time a task wants to add something to the `RequestCache`, so it tries to get the lock.
I've noticed this in Tribler while unloading communities, so this should fix that issue as well.
Personally, I can't think of any situation in which the locks would be required, so we may have to think about removing them altogether.
This PR also:
* Fixes https://github.com/Tribler/py-ipv8/issues/770
* Fixes a memory leak caused by the exit socket `TaskManager` not being shutdown.
* Includes a bunch of smaller fixes.

Fix deadlock while shutting down RequestCache

---

ipv8/REST/attestation_endpoint.py
ipv8/REST/identity_endpoint.py
ipv8/REST/rest_manager.py
ipv8/REST/root_endpoint.py
ipv8/attestation/communication_manager.py
ipv8/attestation/identity/community.py
ipv8/attestation/wallet/community.py
ipv8/test/REST/attestationendpoint/test_attestation_endpoint.py
ipv8/test/REST/identity/test_identity_endpoint.py
ipv8/test/REST/rest_base.py
ipv8/test/attestation/wallet/test_attestation_community.py
ipv8/test/base.py
ipv8_service.py

This PR:
- Adds middleware (CommunicationManager/CommunicationChannel) for dealing with ID 2.0 pseudonyms.
- Adds a new `identity` REST endpoint to replace `attestation` (and a lot of tests 😃).
- Adds the factory method `produce_anonymized_endpoint` to `IPv8` to facilitate clean testing.
- Fixes the name of the `temporary_directory` of `TestBase`.
- Fixes the infinite loop on the main thread in the (old) attestation REST API.
- Adds the ability to specify a JSON body to the REST test base in `make_request`.
- Saves the launch configuration of IPv8 into `IPv8.configuration`.
- Fixes #742
- Fixes #774
Remaining for the roadmap of #733 after this PR are: updating the documentation and adding an access token for the API.

Added v2 ID 2.0 REST API

---

doc/basics/overlay_tutorial.rst
ipv8/configuration.py
ipv8/test/REST/identity/test_identity_endpoint.py
ipv8/test/test_configuration.py

Fixes #777.
This PR adds a builder object to construct IPv8 configurations. A typical example (this loads the DiscoveryCommunity with the default settings):
```python
builder = ConfigBuilder(True).set_address("0.0.0.0") \
.set_port(8090) \
.add_key("anonymous id", "curve25519", "ec_multichain.pem") \
.set_log_level("INFO") \
.set_working_directory(".") \
.set_walker_interval(0.5) \
.add_overlay("DiscoveryCommunity",
"anonymous id",
[WalkerDefinition(Strategy.RandomWalk, 20, {'timeout': 3.0}),
WalkerDefinition(Strategy.RandomChurn, -1, {
'sample_size': 8,
'ping_interval': 10.0,
'inactive_time': 27.5,
'drop_time': 57.5
}),
WalkerDefinition(Strategy.PeriodicSimilarity, -1, {})],
{},
[('resolve_dns_bootstrap_addresses', )])
ipv8 = IPv8(builder.finalize())
```
The overlay tutorial has been …

Added ConfigBuilder

---

doc/conf.py
github_increment_version.py
ipv8/REST/rest_manager.py
setup.py

Fixes #783
This PR modifies the `github_increment_version.py` script such that it updates all mentions of the IPv8 version in the source code.
Two notes:
- The version specified in `setup.py` leads all others.
- Because we modify multiple files at once, we can no longer use the simple GitHub update file API. Now we actually need a _tree_ to pack all the file edits into a single commit.
I'll perform a run of this script, so you can see the output: see #786.

Updated auto version incrementer

---

ipv8/REST/attestation_endpoint.py
ipv8/REST/identity_endpoint.py
ipv8/attestation/wallet/community.py
ipv8/taskmanager.py
ipv8/test/REST/attestationendpoint/test_attestation_endpoint.py
ipv8/test/REST/identity/test_identity_endpoint.py
ipv8/util.py
run_all_tests.py

This PR:
- Uses the best practice of using a multiprocessing `context` for test execution.
- Adds the `-a` option to the script to not spam the logging output for loggers that do not support caret modifications (like our PR testers 😃).
- Adds tracebacks to logging output of failed `TaskManager` tests.
- Doesn't fail when receiving an unknown hash verification request.
- Adds and uses a `wait_for` construction to avoid race conditions in the identity REST tests.
- Fixes the `lstrip` bug.

Various fixes

---

ipv8/attestation/identity/community.py
ipv8/messaging/anonymization/hidden_services.py
ipv8/test/REST/rest_base.py
ipv8/test/messaging/anonymization/test_hiddenservices.py
ipv8/test/mocking/ipv8.py
ipv8_service.py

This PR adds a convenience method to add strategies/overlays to IPv8. This makes sure programmers don't have to worry about acquiring a lock.

Added convenience add strategy method

---

ipv8/attestation/trustchain/caches.py
ipv8/attestation/trustchain/settings.py
ipv8/requestcache.py

I noticed that I frequently have to change these values during Gumby experiments, so I'm converting them to settings.
I also made the `RequestCache` accept integers.

Added settings for the sign timeouts

---

scripts/exitnode_ipv8_only_plugin.py
systemd/ipv8-exit-node@.service

- Added a `.service` file for integration in `systemctl`.
- Fixed the `peer_status` variable when initializing the configuration.
- Added a `statedir` option to the IPv8 exit node script.

Fixed IPv8 exit node script

---

ipv8/attestation/communication_manager.py

After #808 I conducted a full scale sanity check. I also found the `pseudonyms` folder being created in the current working directory instead of the `working_directory` specified by IPv8's configuration.
This PR:
- Makes sure the `pseudonyms` folder is created in the specified `working_directory`.
- Fixes a bug where using the default working dir with an already loaded `IdentityCommunity` would produce a `NoneType` error.

Make pseudonym directory in working directory

---

.github/workflows/python-publish.yml

Fixes #812
This PR:
- Adds GitHub Action integration for PyPi releases.
Note:
This is the default workflow of https://github.com/actions/starter-workflows/blob/930a2cac2bfea6c9d44813a374348d81b7b410fd/ci/python-publish.yml

Added PyPi release GitHub action

---

ipv8/configuration.py
ipv8/messaging/anonymization/community.py
ipv8/messaging/anonymization/tunnel.py
ipv8/test/test_configuration.py

After doing some tunnel performance monitoring, it turns out the circuits are often destroyed well before their time. Unfortunately, this is having a significant negative impact on performance.
Luckily we recently fixed an issue with the `DestroyPayload` not setting the `reason` field, so we can now see why this is happening. As it turns out the circuits are frequently destroyed because of [`check_num_packets`](https://github.com/Tribler/py-ipv8/blob/10836c5f70f0d381a6c808b0d4c24f5e07451d77/ipv8/messaging/anonymization/tunnel.py#L208). Given the fact that this restriction is rather arbitrary to begin with, I'd like to get rid of it.

Removed check_num_packets from TunnelExitSocket

---

doc/basics/overlay_tutorial.rst
doc/further-reading/advanced_identity.rst

Fixes #816
Fixes #818
This PR:
- Adds a description of using X509 certificates for REST API TLS.
- Updates the overlay tutorial to use `ez_send`.

Updates to documentation

---

ipv8/configuration.py
ipv8/test/test_configuration.py

Fixes #824
This PR:
- Removes the `IdentityCommunity` and `AttestationCommunity` from the **default** configuration (they are still configurable for backwards compatibility).

Removed identity communities from default configuration

---

ipv8/messaging/interfaces/dispatcher/endpoint.py
ipv8/messaging/interfaces/endpoint.py
ipv8/messaging/interfaces/udp/endpoint.py
ipv8_service.py

Related to https://github.com/Tribler/py-ipv8/issues/615#issuecomment-667913436
This is the first step in moving from a single universal Endpoint to multiple concurrent Endpoints.
This implementation is fully backwards compatible with our current configuration and usage, also within Tribler.
This PR:
- Adds the DispatcherEndpoint to dispatch to multiple Endpoint implementations (as opposed to choosing just one).
- Adds the UDPv6Endpoint for sending and receiving IPv6 traffic.
Note that we cannot expose this IPv6 functionality yet, as receiving IPv6 traffic will absolutely decimate most Community logic.
Future work also includes having Peers maintain a dictionary of address per interface, instead of just one address.

Added EndpointDispatcher

---

ipv8/REST/rest_manager.py

Fixes #833
This PR:
- Updates the `RESTManager` to allow for custom `RootEndpoint` definition.

Made RootEndpoint configurable

---

ipv8/REST/tunnel_endpoint.py
ipv8/messaging/anonymization/caches.py
ipv8/messaging/anonymization/community.py
ipv8/messaging/anonymization/endpoint.py
ipv8/messaging/anonymization/hidden_services.py
ipv8/messaging/anonymization/payload.py
ipv8/messaging/anonymization/tunnel.py
ipv8/test/messaging/anonymization/test_community.py
ipv8/test/messaging/anonymization/test_datachecker.py
ipv8/test/messaging/anonymization/test_exit_socket.py
ipv8/test/messaging/anonymization/test_hiddenservices.py
ipv8/test/mocking/exit_socket.py

This PR:
- Removes `PEER_FLAG_EXIT_ANY`. From now on we will only use more specific flags: `PEER_FLAG_EXIT_BT/IPV8`.
- Removes `CIRCUIT_TYPE_IPV8`.
- Adds an `exit_flags` argument to `create_circuit` that allows the caller to specify which capabilities the circuit should have.
- Adds speed test functionality to the `TunnelCommunity`. It supports both upload and download tests. End-to-end circuits are also supported. By implementing special messages for the test (test-request/response), we are able to do a speed test without involving an outside source (e.g. a BitTorrent swarm). By adding a new peer flag (`PEER_FLAG_SPEED_TEST`) we extend the tunnel protocol without breaking compatibility.

Added speed test functionality to TunnelCommunity

---

ipv8/messaging/anonymization/community.py
ipv8/messaging/anonymization/hidden_services.py
ipv8/messaging/anonymization/payload.py
ipv8/messaging/anonymization/tunnel.py
ipv8/test/messaging/anonymization/test_community.py
ipv8/test/messaging/anonymization/test_hiddenservices.py

This PR:
- Adds `Payload.msg_id` to the tunnel payload classes, so we can use `add_message_handler`.
- Adds `add_cell_handler` for messages that are wrapped in a `Cell`.
- Fixes some cases in which control packets were not included in `bytes_up/bytes_down`.
- Adds `vp_compile` decorator wherever possible to speed up message serialization.
- Renames `tc_lazy_wrapper_unsigned` to `unpack_cell`.

Add message ID to tunnel payload classes

---

ipv8/messaging/anonymization/tunnel.py

In Python 3.8, `CancelledError` no longer inherits from `Exception`, so we'll have to catch it separately.

Catch CancelledError in on_ip_address

---

ipv8/messaging/interfaces/endpoint.py
ipv8/test/mocking/endpoint.py

Fixes #844
This PR:
- Fixes LAN estimation for EndpointListener subclasses.
Previously `my_estimated_lan` would falsely report its address before the port was actually claimed. Now it is extra broken through the `DispatcherEndpoint` PR. With this PR the address is now reported as `("0.0.0.0", 0)` if the endpoint is still unclaimed/closed, compatible with the introduction requests and responses.
As we are now checking `is_open` in the partially intialized `AutoMockEndpoint`, we require some small fixes there too.

Fixed EndpointListener LAN estimation

---

ipv8/keyvault/public/m2crypto.py
ipv8/test/keyvault/test_crypto.py

Fixes https://github.com/Tribler/py-ipv8/pull/843#issuecomment-672791520 as reported by @egbertbouman .
This PR:
- Fixes `M2CryptoSK.verify` always returning `False`.
- Updates `M2CryptoPK.verify` to not strip all prepended `b'\x00'` characters manually from `r` and `s` and instead use `lstrip()`.
- Updates `test_sign_and_verify_m2crypto` to behave the same as `test_sign_and_verify_libnacl`.

Fixed M2CryptoSK.verify

---

ipv8/attestation/trustchain/community.py
ipv8/attestation/trustchain/payload.py
ipv8/attestation/wallet/community.py
ipv8/attestation/wallet/payload.py
ipv8/community.py
ipv8/dht/community.py
ipv8/dht/discovery.py
ipv8/dht/payload.py
ipv8/messaging/payload.py
ipv8/peerdiscovery/community.py
ipv8/peerdiscovery/payload.py

This PR:
- Updates all Payload instances to maintain their own message identifier.
- Updates all internal message handler registration to use the Payload definitions.
This is all so we can easily change `decode_map` from a `{str -> function}` mapping to a `function[256]` list (this is possible because all decode_map entries are the `chr()` value of a single byte). This will be in a separate PR and save memory and improve speed.

Don't use decode_map directly for message handlers

---

ipv8/REST/overlays_endpoint.py
ipv8/community.py

This PR:
- Fixes `deprecated_message_names` indexing on `chr` and being looked-up with `int`.
- Updates `decode_map` to be a list instead of a dictionary.
This _should_ be faster and more memory efficient. I'll produce some perfomance results soon, if this is not faster I'll close this PR again.

Switch decode_map to list

---

ipv8/messaging/interfaces/dispatcher/endpoint.py
ipv8/messaging/interfaces/endpoint.py
ipv8/messaging/interfaces/udp/endpoint.py
ipv8/test/mocking/endpoint.py

Fixes #851
This PR:
- Adds `Endpoint.reset_byte_counters` to reset the `bytes_up` and `bytes_down` counters back to `0`.

Added easy way to reset Endpoint byte counters

---

ipv8/test/mocking/exit_socket.py

Fixes #849
This PR:
- Fixes MockTunnelExitSocket raising the wrong error

Fixed wrong error in MockTunnelExitSocket

---

doc/index.rst

Fixes #854
This PR:
- Updates the documentation `index.rst` to include the advanced identity documentation.

Added advanced identity doc to TOC

---

CONTRIBUTING.md
github_increment_version.py

This PR:
- Adds alphabetical sorting for the GitHub release script.
- Adds automated erroneous prefix stripping for the GitHub release script.
- Updates `CONTRIBUTING.md` with the two-step release workflow for administrators.
- Updates `CONTRIBUTING.md` with naming conventions for contributors.

Updated the GitHub release script and its instructions

---

ipv8/messaging/interfaces/dispatcher/endpoint.py

Fixes #862
This PR:
- Fixes calling `DispatcherEndpoint.send()` with an address for an unloaded interface.

READY: Fix sending to unsupported guessed interface

---

ipv8/test/base.py

Fixes #864
Fixes #865 
This PR:
- Updates `TestBase.setUpClass` to detect `pytest` and disable the class lock-up detection.
- Updates `TestBase.temporary_directory` to use `uuid` instead of 10x `random.choice`.
Note: the body of the if-statement for the first change is the same as before.

Added pytest support

---

ipv8/messaging/interfaces/dispatcher/endpoint.py
ipv8/test/messaging/interfaces/dispatcher/test_endpoint.py

This PR:
- Adds unit tests for the DispatcherEndpoint.
- Fixes a bug in the DispatcherEndpoint when a packet is sent to a known, but unloaded interface.

Added unit tests for DispatcherEndpoint

---

ipv8/messaging/interfaces/endpoint.py

Fixes #868
This PR:
- Fixes `EndpointListener` accessing the private (and possibly non-existent) member `._port` of `Endpoint`s.

Fixed EndpointListener accessing Endpoint._port

---

ipv8/REST/asyncio_endpoint.py

Fixes #870
This PR:
- Fixes the `AsyncioEndpoint` removing all subclasses of `DriftMeasurementStrategy` on disable.

Don't remove all other observers in AsyncioEndpoint

---

.pylintrc

Fixes #875
This PR:
- Fixes `ignore-patterns` expecting a regular expression.

Fixed pylintrc regular expression

---

doc/reference/serialization.rst
ipv8/REST/attestation_endpoint.py
ipv8/REST/isolation_endpoint.py
ipv8/attestation/trustchain/block.py
ipv8/attestation/trustchain/community.py
ipv8/attestation/wallet/community.py
ipv8/attestation/wallet/primitives/cryptography_wrapper.py
ipv8/community.py
ipv8/dht/community.py
ipv8/dht/provider.py
ipv8/lazy_community.py
ipv8/messaging/anonymization/community.py
ipv8/messaging/anonymization/hidden_services.py
ipv8/messaging/anonymization/payload.py
ipv8/messaging/deprecated/encoding.py
ipv8/messaging/lazy_payload.py
ipv8/messaging/payload.py
ipv8/messaging/serialization.py
ipv8/peerdiscovery/community.py
ipv8/test/dht/test_community.py
ipv8/test/keyvault/test_signature.py
ipv8/test/messaging/anonymization/test_community.py
ipv8/test/messaging/test_lazy_payload.py
ipv8/test/messaging/test_serialization.py
ipv8/test/peerdiscovery/test_community.py
ipv8/util.py

This PR:
* Updates `Serializer` to make it more efficient
* Updates `EZPackOverlay` so that there is less string slicing and fewer lists are being created
* Renames the (un)packing functions that take a `Serializable` as an argument
* Removes `pack(_multiple)`/`unpack(_multiple)` functions
* Removes `optional_format_list` as its use is limited, and it's hurting unpacking performance. I've intentionally put this in a separate commit, so it's easy to undo in case we decide to keep it.
With the updated serializer, the time spent (un)serializing typically decreases by 20+%.
For instance, for intro-request/responses the decrease varies between 21-38%. Currently:
```
Serializing 1,000,000 intro-request packets: 5.6937067 s
Serializing 1,000,000 intro-response packets: 7.4839985 s
Unserializing …
```

 Updated Serializer to be more efficient

---

doc/basics/overlay_tutorial.rst
doc/reference/serialization.rst
ipv8/REST/attestation_endpoint.py
ipv8/REST/overlays_endpoint.py
ipv8/REST/schema.py
ipv8/attestation/identity/community.py
ipv8/attestation/trustchain/community.py
ipv8/attestation/wallet/community.py
ipv8/community.py
ipv8/database.py
ipv8/dht/churn.py
ipv8/dht/community.py
ipv8/messaging/anonymization/community.py
ipv8/messaging/anonymization/payload.py
ipv8/messaging/anonymization/pex.py
ipv8/overlay.py
ipv8/peerdiscovery/community.py
ipv8/peerdiscovery/network.py
ipv8/test/REST/rest_base.py
ipv8/test/base.py
ipv8/test/messaging/anonymization/test_hiddenservices.py
ipv8/test/peerdiscovery/test_community.py
ipv8/test/peerdiscovery/test_edge_discovery.py
ipv8/test/peerdiscovery/test_random_discovery.py
ipv8/util.py
scripts/tracker_plugin.py
scripts/trustchain_crawler_plugin.py
stresstest/bootstrap_rtt.py
stresstest/peer_discovery.py
stresstest/peer_discovery_defaults.py

This PR:
* Replaces the `master_peer` of every `Community` with a byte string. In the past, this was used by `Dispersy` as part of a mechanism to remotely shutdown a `Community`. However, since we no longer have this feature, we can easily replace this with a byte string.
* Removes `cast_to_chr` and `char_to_unicode` that were used while porting from Python 2 to 3.
* Possibly fixes intermittent "unregistered address" error during `EdgeWalk` tests.

Replaced master_peer with a 20-byte community_id

---

ipv8/messaging/serialization.py

Fixes #881
This PR:
- Adds the `q` format (`>q`) to the Serializer's default loaded formats.

Added 'q' format to Serializer defaults

---

ipv8/loader.py
ipv8/test/test_loader.py

Fixes #884
This PR:
- Adds unit tests for the `CommunityLauncher` and `CommunityLoader` classes.
- Adds decorators for the `CommunityLauncher` methods (`after`, `kwargs`, `name`, `overlay`, `precondition`, `set_in_session`, `walk_strategy`).
- Updates `CommunityLauncher` to no longer be an abstract base class, but raise a `RuntimeError` instead (this is more linter friendly).
Some examples:
```python
@after("LoadMeFirstCommunity")
@precondition('session.is_my_community_enabled')
@overlay(MyCommunity)
@walk_strategy('ipv8.peerdiscovery.discovery', 'RandomWalk', target_peers=-1)
class CustomCommunityLauncher(CommunityLauncher):
pass
@name('MyCommunity')
@precondition('session.on_testnet()')
@overlay('some_module.another_module', 'MyTestnetCommunity')
class …
```

Added CommunityLauncher decorators

---

doc/basics/identity_tutorial.rst
doc/basics/identity_tutorial_1.py
doc/basics/overlay_tutorial.rst
doc/basics/overlay_tutorial_1.py
doc/basics/overlay_tutorial_2.py
doc/basics/overlay_tutorial_3.py
doc/basics/overlay_tutorial_4.py
doc/basics/overlay_tutorial_5.py
doc/deprecated/attestation_tutorial.rst
doc/deprecated/attestation_tutorial_1.py
doc/further-reading/advanced_identity.rst
doc/further-reading/advanced_identity_1.py
doc/further-reading/advanced_identity_2.py
doc/reference/serialization.rst
doc/reference/serialization_1.py
doc/reference/serialization_2.py
doc/reference/serialization_3.py

First step for #872.
This PR:
- Updates the documentation to include examples from stand-alone files, instead of embedding them.
- Updates the serialization documentation to prefer `ez_send` over `ezr_pack`.
This is the "easy" part of #872. In a following PR I will add new functionality to run these examples and check for errors.

Extracted documentation examples into Python files

---

doc/further-reading/advanced_identity.rst
doc/further-reading/advanced_identity_1.py
doc/further-reading/advanced_identity_2.py
doc/validate_examples.py

Related to #872
This PR:
- Adds a script to run all examples, isolated, defined in the `doc` folder.
- Fixes the advanced identity tutorial feeding arguments to `RESTManager()` instead of `RESTManager.start()`.
This script will wait for up to 30 seconds for each example to finish, otherwise it terminates it.
The output of each example is inspected to check for tracebacks.
Script output:
```
$ python3 validate_examples.py 
Killed overlay_tutorial_4.py after 30 seconds!
[SUCCESS] No tracebacks detected in overlay_tutorial_4.py
Killed overlay_tutorial_3.py after 30 seconds!
[SUCCESS] No tracebacks detected in overlay_tutorial_3.py
Killed overlay_tutorial_1.py after 30 seconds!
[SUCCESS] No tracebacks detected in overlay_tutorial_1.py
Killed overlay_tutorial_5.py after 30 seconds!
[SUCCESS] …
```

Added documentation examples validation script

---

ipv8/loader.py
ipv8/test/test_loader.py

Related to https://github.com/Tribler/tribler/issues/5647
This PR:
- Adds a `hiddenimports` field to all `CommunityLauncher` classes to provide hints to PyInstaller about what modules will be lazy-loaded.

Added hiddenimports to CommunityLauncher

---

doc/reference/serialization.rst
ipv8/dht/community.py
ipv8/dht/discovery.py
ipv8/dht/payload.py
ipv8/lazy_community.py
ipv8/messaging/serialization.py
ipv8/test/messaging/test_serialization.py

This PR:
* Adds the ability to register new packers with the `Serializer`.
* Adds `ListOf` that allows for almost any packer (except for `NestedPayload` and `Raw`) to be turned into a list.
Now you can do stuff like `serializer.add_packer('infohashes', ListOf(DefaultStruct('20s')))`.
Besides its use in the `DHTCommunity`, I'd also like to use it in the `TunnelCommunity` payloads and get rid of `encode`/`decode`.
* Adds `ipv4` packer as an alternative to `4SH`. The advantage of this packer is that it deals with IP address serialization and avoids the use of `fix_` functions.
* Removes global time from DHT payloads  Since we're breaking the tunnel protocol by changing the payout mechanism in Tribler, this is a good time to update the DHT protocol.
* Removes `send_message` from the …

Updated DHTCommunity serialization

---

ipv8/test/mocking/ipv8.py

For some Tribler test, I require to manually unload a specific overlay. Therefore, I propose to add this method to the mock IPv8 class. Note that this method is also there in the real IPv8 class.
This PR:
- Adds the `unload_overlay` method to `MockIPv8`.

Added unload_overlay to mock IPv8

---

ipv8/dht/discovery.py
ipv8/test/REST/rest_base.py
ipv8/test/base.py
ipv8/test/dht/test_community.py
ipv8/test/messaging/anonymization/test_hiddenservices.py
ipv8/test/mocking/ipv8.py

This is consistent with the real IPv8 object, which does not have an unload but a stop method.
This PR:
- Renames MockIPv8.unload to MockIPv8.stop
- Fixes a typo in the DHT community

Renamed MockIPv8.unload to MockIPv8.stop

---

ipv8/REST/base_endpoint.py
ipv8/attestation/communication_manager.py
ipv8/attestation/identity/attestation.py
ipv8/attestation/identity/community.py
ipv8/attestation/identity/database.py
ipv8/attestation/identity/manager.py
ipv8/attestation/identity/metadata.py
ipv8/attestation/identity/payload.py
ipv8/attestation/schema/manager.py
ipv8/attestation/signed_object.py
ipv8/attestation/tokentree/token.py
ipv8/attestation/tokentree/tree.py
ipv8/attestation/wallet/irmaexact/gabi/builder.py
ipv8/attestation/wallet/irmaexact/gabi/keys.py
ipv8/attestation/wallet/irmaexact/gabi/proofs.py
ipv8/attestation/wallet/primitives/value.py
ipv8/configuration.py
ipv8/database.py
ipv8/messaging/interfaces/dispatcher/endpoint.py
ipv8/messaging/lazy_payload.py
ipv8/messaging/serialization.py
ipv8/peer.py
ipv8/types.py
mypy.ini

Fixes #879
This PR:
- Adds a top-level file for typing, reducing the amount of imports only used for typing (possibly creating circular dependencies).
- Adds support for running Mypy on the codebase (using `mypy ipv8` from the root folder).
- Fixes Mypy errors (fixing errors includes adding missing types in some cases).
Note that this PR **does not** add typing to the entire codebase: it only fixes what was already there.
- Use PEP 563 for class and static methods. For example:
```python
from __future__ import annotations  # Included PEP 563 in Python 3.7
class A:
@classmethod
def create(cls) -> A:  # This wont work without the future import, A is not defined/loaded yet
return cls
```
- Use PEP 484 and PEP 563 to avoid circular imports and unnecessary/typing-only imports:
```python
if …
```

Added static typing support

---

ipv8/messaging/interfaces/statistics_endpoint.py
ipv8/test/messaging/interfaces/dispatcher/test_endpoint.py
ipv8/test/messaging/interfaces/test_network_stats.py
ipv8/test/messaging/interfaces/test_statistics_endpoint.py
ipv8_service.py

This PR:
- Adds unit tests for the `DispatcherEndpoint`.
- Adds unit tests for `NetworkStat`.
- Adds unit tests for the `StatisticsEndpoint`.
- Fixes a bug in `StatisticsEndpoint` that pulled `bytes_down` from `self.statistics[identifier].bytes_down` instead of `self.statistics[prefix][identifier].bytes_down`.
- Removes the unused `ipv8` attribute from `StatisticsEndpoint`.

Added Endpoint unit tests

---

ipv8/messaging/anonymization/caches.py
ipv8/messaging/anonymization/community.py
ipv8/messaging/anonymization/hidden_services.py
ipv8/messaging/anonymization/payload.py
ipv8/messaging/anonymization/tunnel.py
ipv8/messaging/anonymization/tunnelcrypto.py
ipv8/messaging/lazy_payload.py
ipv8/messaging/serialization.py
ipv8/test/messaging/anonymization/test_community.py
ipv8/test/messaging/anonymization/test_hiddenservices.py
ipv8/test/messaging/test_lazy_payload.py
ipv8/test/messaging/test_serialization.py

This PR breaks compatibility with the current version of the `TunnelCommunity` and does the following:
* Removes the nested decorator from `unpack_cell` as it's hurting performance.
* Updates the tunnel payload to use the new ipv4 packer.
* Adds the relay_early flag to `CellPayload` in order to limit the maximum length of a circuit.
* Switches to `libnacl` with AES-256-GCM for tunnel crypto, giving an increase in throughput of about 25%.
* Adds an identifier field to create(d)/extend(ed).
* Adds functions for manual (un)packing to the `Serializer`.
* Removes the use of `encode`/`decode` throughout the `TunnelCommunity`.
* Updates `DataPayload` to use the IPv8 `Serializer`. With the recent changes to the `Serializer`, it's fast enough to use for tunnel data. I measured a small decrease in …

Updated TunnelCommunity payloads and crypto

---

ipv8/messaging/anonymization/caches.py
ipv8/messaging/anonymization/community.py
ipv8/messaging/anonymization/hidden_services.py

This PR:
* Updates `CreateRequestCache` to use the payload identifier.
* Removes `select_circuit` from `TunnelCommunity` as this functionality has moved to `Dispatcher`.

Update CreateRequestCache to use the payload identifier

---

ipv8/community.py
ipv8/test/peerdiscovery/test_community.py

Fixes #903
This PR:
- Updates `resolve_dns_bootstrap_addresses()` to run in a daemon thread.
- Updates `resolve_dns_bootstrap_addresses()` to not add duplicates to the `_DEFAULT_ADDRESSES`.
Note (#903): this deliberately avoids `asyncio`.

Added deferred bootstrap DNS resolution

---

ipv8/community.py
ipv8/peerdiscovery/community.py

Fixes #905
This PR:
- Updates the logging level for too many peers to `DEBUG`.

Updated "too many peers" log level to DEBUG

---

ipv8/messaging/anonymization/community.py
ipv8/messaging/anonymization/hidden_services.py
ipv8/messaging/anonymization/payload.py
ipv8/messaging/anonymization/pex.py
ipv8/messaging/interfaces/udp/endpoint.py
ipv8/messaging/serialization.py
ipv8/test/messaging/anonymization/test_community.py

This PR:
* Adds the `Address` packer to the default `Serializer`. Unfortunately, to maintain compatibility with the `TunnelCommunity`, it's using a `varlenH` for domain names (wasting an extra byte).
* Updates `CellPayload` to catch the correct exception while doing crypto.
* Updates `PexCommunity` to stop using encode/decode. Now that `TrustChain` is the only community still using it, this functionality can be removed in the future (see https://github.com/Tribler/py-ipv8/issues/908).
Note that the `PexCommunity` does a +1 on the `community_id`, instead of using `version_id`. This is because the trackers aren't looking at the first 2 bytes of the prefix, which could lead to being introduced to old `PexCommunities`. This would make peer discovery take longer.

Add address packer to default Serializer

---

ipv8/attestation/trustchain/community.py
ipv8/community.py
ipv8/messaging/anonymization/community.py
ipv8/messaging/anonymization/pex.py
ipv8/messaging/interfaces/endpoint.py
ipv8/messaging/interfaces/udp/endpoint.py
ipv8/messaging/lazy_payload.py
ipv8/messaging/payload.py
ipv8/messaging/serialization.py
ipv8/peer.py
ipv8/peerdiscovery/community.py
ipv8/peerdiscovery/discovery.py
ipv8/peerdiscovery/network.py
ipv8/test/messaging/test_lazy_payload.py
ipv8/test/mocking/endpoint.py
ipv8/test/peerdiscovery/test_community.py
ipv8/test/test_peer.py
ipv8_service.py
stresstest/peer_discovery.py

Fixes #912 
Related to #615 
This PR:
- Adds `get_ipv6_address` to intially guess the IPv6 address.
- Adds support for IPv6 addresses in `Community`.
- Adds hand-off from the current address to the preferred address (using `my_preferred_address()`) in `Community` (practically usually IPv4 bootstrap into IPv6).
- Adds `AutoMockEndpoint.ADDRESS_TYPE` to switch between `"UDPv4Address"` and `"UDPv6Address"` during unit tests.
- Fixes `'bits'` serialization:
- Fixes `'bits'` being unpacked in reverse order.
- Fixes `VariablePayload` not working with the `'bits'` packer.
- Updates `Peer` to prefer `IPv6` over `IPv4`.
- Updates `IPv8` to load the `UDPIPv6` interface.
- Updates `Payload`'s location to `serialization.py` instead of `payload.py`, so classes in `payload.py` can use …

Community base class IPv6 support

---

stresstest/bootstrap_rtt.py

This PR:
- Fixes `bootstrap_rtt.py` using old tuple -> address resolution.

Fixed Bootstrap script resolving IPv6 tuples

---

ipv8/requestcache.py

Fixes #917
This PR:
- Updates `NumberCache.on_timeout()` to no longer `raise NotImplementedError` if not overwritten in a subclass.

Updated NumberCache.on_timeout to no longer be abstract

---

ipv8/community.py

Fixes #915 
This PR:
- Replaces the end-of-life tracker with a new working one
Update to the DNS entry to be done after the PR is merged

Replace end-of-life tracker

---

scripts/tracker_plugin.py

This PR:
- Fixes `EndpointServer.get_peer_for_introduction` to comply with the new IPv6 interface changes.

Fixed tracker peer for intro overwrite

---

scripts/exitnode_ipv8_only_plugin.py

This PR:
- Adds Sentry support for the exit node script
```bash
python -m pip install sentry-sdk
```
nix:
```bash
EXPORT SENTRY_URL=<sentry_url>
```
windows:
```windows shell
SETX SENTRY_URL <sentry_url>
```
Changes in ansible roles: https://github.com/Tribler/tribler-ansible-roles/pull/1
PS: cool PR template 👍

Add Sentry support to the exit node script

---

ipv8/test/REST/test_overlays_endpoint.py

This PR:
- Adds tests for the `/overlays` REST endpoint.

Added tests for the REST overlays endpoint

---

ipv8/REST/isolation_endpoint.py
ipv8/test/REST/test_isolation_endpoint.py

This PR:
- Adds tests for the `/isolation` REST endpoint.
- Updates `IsolationEndpoint` to add bootstrap nodes to the `network.blacklist`.

Added isolation endpoint tests

---

ipv8/peerdiscovery/network.py
ipv8/test/peerdiscovery/test_network.py

This PR fixes an issue that causes trackers (and other nodes) to introduce peers to outdated addresses. This is due to outdated peer information getting stuck in the `service_cache`. It's a bit difficult to explain what happens, but it boils down to this:
* Peer A *first* sends an intro-req to Peer B for community X and *then* for community Y.
* Peer A updates its address.
* Peer A sends another intro-req to Peer B for communities X & Y.
Now in community X, peer B will use the correct addresses when sending intro-responses. However, in community Y peer B will still use the old address.
I've intentionally used the same instance in the cache as the one in `verified_peers`, to prevent future issues (like losing IPv6 addresses).

Fix for introducing peers to outdated addresses

---

ipv8/REST/dht_endpoint.py
ipv8/configuration.py
ipv8/dht/churn.py
ipv8/dht/community.py
ipv8/dht/discovery.py
ipv8/dht/payload.py
ipv8/dht/provider.py
ipv8/dht/routing.py
ipv8/messaging/anonymization/community.py
ipv8/messaging/anonymization/hidden_services.py
ipv8/messaging/anonymization/pex.py
ipv8/messaging/serialization.py
ipv8/test/dht/base.py
ipv8/test/dht/test_churn.py
ipv8/test/dht/test_community.py
ipv8/test/dht/test_discovery.py
ipv8/test/dht/test_routing.py
ipv8/test/test_configuration.py

This PR partially addresses https://github.com/Tribler/py-ipv8/issues/615 and adds IPv6 support to the `DHTCommunity`.
IPv6 support works as follows: 
All nodes in the network are identified by an ID that is partially based on the IP address that is used while sending DHT messages. Since we can now receive messages over multiple interfaces, I've added a `RoutingTable` and `Storage` object for each interface. Which of these objects is used while processing a query is decided based on the query's source address. This ensures that all nodes in the `RoutingTable` will be of the same address type, which also means that a response with nodes can only be of the same address type as was used when sending the request. When `find_values` or `find_nodes` is called, the `DHTCommunity` will perform a …

Added IPv6 support to DHTCommunity

---

ipv8/loader.py
ipv8/test/test_loader.py

This PR:
Adds the ability to load overlay and walk strategy from "function class representation" to have both explicit imports and lazy loading:
``` python
def GigaChannelCommunity():
from tribler_core.modules.metadata_store.community.gigachannel_community import GigaChannelCommunity
return GigaChannelCommunity
...
@overlay(GigaChannelCommunity)
class GigaChannelCommunityLauncher(IPv8CommunityLauncher):
pass
```
Reference: https://github.com/Tribler/tribler/pull/5746

Add overlay and walk strategy loading from a function

---

ipv8_service.py

Fixes #933
This PR:
- Updates IPv8 to allow anonymization of-and statistics for-custom endpoints (set through `endpoint_override`).

Fixed setting anonymization and statistics for overwritten endpoints

---

ipv8/community.py
ipv8/test/test_community_compat.py

Fixes #937
This PR:
- Fixes introduction responses suggesting to new-style introduced peers that the old-style peer they need to puncture is new-style based on the introduced peer's new-style setting instead of the setting of the peer they need to puncture.

Fixed new style punctures sent to old style peers

---

ipv8/lazy_community.py
ipv8/peerdiscovery/community.py
ipv8/types.py

Related to #930
This PR:
- Adds a decorator to retrieve caches from the `self.request_cache`, based on current conventions.
- Updates the `lazy_community.py` file to include typing information.
The [changes in `ipv8/peerdiscovery/community.py`](https://github.com/Tribler/py-ipv8/pull/941/files#diff-18cfe7b973063f93e725765c4786b43a22d2306573de889ea3a340b99d3e631e) show how this decorator can be used.

Added cache retrieval wrapper

---

ipv8/lazy_community.py
ipv8/peerdiscovery/network.py
ipv8/test/peerdiscovery/test_network.py
ipv8/types.py

Fixes #935
This PR:
- Adds automatic resolution of known peers in `lazy_community.py` `lazy_wrapper*` decorators.
- Adds typing information to `Network`.
- Adds `verified_by_public_key_bin` to `Network` for quicker lookups per public key.
- Updates `Network` attribute comments to be attribute docstrings (you can now press `Ctrl+Q` on them 😃).
- Updates `Network.services_per_peer` to use the full public key material instead of an mid.
- Updates `TestNetwork` to use `bytes` as overlay ids.
Notable deviation from proposed fix in #935: decided not to go with best performance, but simple one line lookups (thanks @kozlovsky). This class is cryptic and fagile enough, we don't need even more mystical constructs.

Network class polishing

---

ipv8_service.py

Fixes #943
This PR:
- Removes `UDPIPv6` from the default endpoints loaded by `IPv8`.

Remove UDPIPv6 from default endpoints

---

ipv8/lazy_community.py

Fixes #948
This PR fixes the incorrect result signature of EZPackOverlay._ez_unpack_auth:
Incorrect: `Tuple[BinMemberAuthenticationPayload, List[Payload], bytes]`
Correct: `Tuple[BinMemberAuthenticationPayload, GlobalTimeDistributionPayload, Payload]`

Fixed result signature for EZPackOverlay._ez_unpack_auth

---

ipv8/dht/community.py
ipv8/dht/provider.py
ipv8/test/dht/test_provider.py

This PR:
* Fixes a serialization issue that occurred after the IPv6 port.
* Updates serialization code to use `VariablePayload`, as it's much less error-prone than serializing manually.
* Updates DHT community ID.
* Adds tests for `DHTCommunityProvider`

Fixed DHTCommunityProvider serialization

---

ipv8/test/base.py

This PR:
- Fixes not awaiting the `asynctest.helpers.exhaust_callbacks` coroutine in the `TestBase.tearDown` method.

Properly await exhaust_callbacks in TestBase

---

ipv8/messaging/interfaces/udp/endpoint.py

Fixes https://github.com/Tribler/tribler/issues/5830
This PR fixes `AttributeError: 'NoneType' object has no attribute 'call_exception_handler'` by adding `AttributeError` to ignored exceptions.

Fixed UDPEndpoint.send when transport is None

---

doc/basics/overlay_tutorial_3.py
doc/basics/overlay_tutorial_4.py
doc/basics/overlay_tutorial_5.py
doc/deprecated/attestation_tutorial_integration/main.py
ipv8/attestation/identity/community.py
ipv8/configuration.py
stresstest/peer_discovery.py

Fixes #956
Fixes #958
This PR:
- Fixes validation tests not using new bootstrapping logic.
- Fixes identity community not spawning with a bootstrapper.
- Fixes `peer_discovery.py` stresstest not using new bootstrapping logic.

Fixed scripts due to bootstrap refactoring

---

doc/index.rst

There were no issues with the request cache documentation generation: https://py-ipv8.readthedocs.io/en/latest/basics/requestcache_tutorial/
This PR adds the tutorial to the documentation TOC so it is visible to the public.

Added request cache documentation to TOC

---

ipv8/loader.py
ipv8/test/test_loader.py

Right now when calling `CommunityLoader.set_launcher` IPv8 imports the community (which happens when calling `CommunityLauncher.get_name`). However, since the `precondition` can fail, this import may be unneeded. This requires us to have the dependencies of the community installed, even if it's disabled.
As a workaround, I suggest changing `CommunityLauncher.get_name` to simply return the name of the launcher itself, rather than that of the community.

Changed the name of CommunityLauncher

---

ipv8/messaging/anonymization/community.py

This PR adds `TunnelSettings.from_dict` classmethod. This method is useful, because sometimes it is necessary to adjust settings in constructor of a class inherited from `TunnelCommunity` before passing them to `TunnelCommunity.__init__`, and it is easier to convert settings from dict to `TunnelSettings`  before modifying them:
```python
class SomeTunnelCommunity(TunnelCommunity):
def __init__(self, *args, **kwargs):
settings = kwargs.pop('settings', TunnelSettings())
if isinstance(settings, dict):
settings = TunnelSettings.from_dict(settings)  # <-- new method
settings.peer_flags.add(SOME_FLAG)
super(SomeTunnelCommunity, self).__init__(*args, settings=settings, **kwargs)
```

Add TunnelSettings.from_dict classmethod

---

ipv8/community.py
ipv8/messaging/interfaces/endpoint.py

Right now it's possible for any peer to overwrite the WAN address of a `Community` with a LAN address. It just needs to set the `IntroductionResponse.destination_address` to a LAN address that could be part of our LAN. (That's easy to do since we're gossiping our own LAN address.) This problem shouldn't occur when `netifaces` is not installed, as `address_is_lan` works differently without `netifaces`.
If the walker continues to walk, this problem would resolve itself right after the next introduction-response. But if the walker stops that address would remain in `my_estimated_wan`. That's the problem that I'm seeing on our exit nodes: eventually, most nodes seem to start putting LAN addresses on the DHT. Maybe some students are playing with our protocol.
Admittedly, a similar problem …

Fixed estimated WAN address being set to a LAN address

---

ipv8/bootstrapping/bootstrapper_interface.py
ipv8/bootstrapping/dispersy/bootstrapper.py
ipv8/bootstrapping/udpbroadcast/bootstrapper.py
ipv8/community.py
ipv8/configuration.py
ipv8_service.py

Fixes #972 (this PR follows the approach presented in this issue)
This PR:
- Adds a bootstrapper based on UDP broadcasts.
- Adds `unload()` to bootstrapper interface.
This is my test script (which I run on separate machines):
```python
import os
from asyncio import ensure_future, get_event_loop
from pyipv8.ipv8.community import Community
from pyipv8.ipv8.configuration import Bootstrapper, BootstrapperDefinition, ConfigBuilder, Strategy, WalkerDefinition
from pyipv8.ipv8_service import IPv8
class MyCommunity(Community):
community_id = b'testudpbroadcast\x00\x00\x00\x00'
def started(self):
async def print_peers():
print("I am:", self.my_peer, "\nI know:", [str(p) for p in self.get_peers()])
self.register_task("print_peers", print_peers, interval=5.0, delay=0)
async def start_communities(): …
```

Added UDP broadcast bootstrapper

---

ipv8/requestcache.py
ipv8/test/test_requestcache.py

Fixes #987
This PR:
- Adds the `RequestCache.passthrough()`, as described in #987.
- Updates `TestRequestCache` to use a common `self.request_cache` to reduce code duplication.
Note that the `passthrough()` does not allow nesting.

Added RequestCache.passthrough()

---

doc/basics/testbase_tutorial.rst
doc/index.rst

This is the follow-up PR on #990.
The output of #990 can be found here: https://py-ipv8.readthedocs.io/en/latest/basics/testbase_tutorial/
No big surprises, everything seems ready to be exposed to the outside world.
This PR:
- Adds the `Unit Testing Overlays` documentation to the index, exposing it.
- Fixes `Unit Testing Overlays` documentation referring to itself as a "file".

Finalized TestBase docs

---

CONTRIBUTING.md

This PR:
- Fixes a grammatical error in `CONTRIBUTING.md`: "number of lines" instead of "amount of lines".

Fixed CONTRIBUTING.md grammar

---

ipv8/REST/tunnel_endpoint.py
ipv8/messaging/anonymization/community.py
ipv8/messaging/anonymization/hidden_services.py
ipv8/messaging/anonymization/utils.py

This PR:
* Updates hidden services to no longer process incoming IPv8 packets wrapped in data cells. Once the end-to-end circuit is fully established this is no longer needed, and could lead to potential security issues.
* Updates the speed test endpoint to allow more control over the number and size of the packets.
* Fixes an issue where the byte counters of the hidden swarm would be reset after an end-to-end circuit is destroyed.

Updated hidden services to disallow IPv8 packets over end-to-end circuits

---

ipv8/peer.py

This PR:
- Updates the type of the `key` attribute passed to the constructor of the `Peer` class.

The key when creating a Peer can also be bytes

---

doc/simulation/simulation_tutorial.rst
simulation/simulation_endpoint.py

This PR:
- Adds support for link latencies in the simulator. Specifically, we modified the `SimulationEndpoint` class to achieve this.

Added link latencies to the IPv8 simulator

---

ipv8/messaging/interfaces/endpoint.py

Fixes #997
This PR:
- Fixes `EndpointListener._local_interfaces` not being initialized in the `__init__`.

Initialize EndpointListener._local_interfaces

---

doc/simulation/simulation_tutorial.rst
doc/simulation/simulation_tutorial_2.py

Fixes #(issue number)
This PR:
- Extends the simulation tutorial with a simple example of how to leverage the IPv8 bootstrap server.

Extended simulation tutorial with bootstrap server

---

ipv8/community.py

This PR:
- When creating a new community, there is a log entry that prints the community name and the prefix. The prefix is hexlified but not decoded, leading to b'' in the log entry. This commit changes this behaviour so that the prefix is decoded after hexlification.

Decoding prefix before printing

---

ipv8/test/base.py
ipv8/test/messaging/anonymization/mock.py
ipv8/test/messaging/anonymization/test_community.py
ipv8/test/messaging/interfaces/udp/test_endpoint.py

Related to Tribler issue https://github.com/Tribler/tribler/issues/6087
This PR:
- Adds support for missing event loops at module load time of `TestBase`.
- Fixes `test_send_many_messages` not finishing in time on the Windows tester.
- Updates `MockDHTProvider` to be in its own file. This allows pytest to import it without rewriting the file.
Notes:
- This is the first time I've seen our Windows PR tests fail (see test result of commit `61f6061`) on `test_send_many_messages`. The machine may be overloaded.
- This may not fix the root issue of https://github.com/Tribler/tribler/issues/6087, but at least brings us one step closer to the source.

READY: Fix pytest compatibility

---

.github/workflows/python-publish-taskmanager.yml
create_setup_taskmanager.py

This PR:
- Adds a script that allows `TaskManager` to be published as a standalone pypi package `ipv8_taskmanager`*.
- Adds a GitHub actions action that allows automatic publishing of the pypi package.
*I chose this name as it makes it easy to port `from ipv8.taskmanager import TaskManager` to `from ipv8_taskmanager import TaskManager`.
The black magic in this file is used to inject the `from .util import coroutine, succeed` imports straight into the `TaskManager` file.

Added script to publish standalone TaskManager

---

.github/workflows/python-publish-taskmanager.yml

This PR:
- Fixes the `ipv8_taskmanager` publisher using a token only valid for `py-ipv8`.

Fixed missing token for TaskManager PyPi project

---

CONTRIBUTING.md

Fixes #1010
This PR:
- Updates `CONTRIBUTING.md` to also exempt contributions to the unit tests from requiring a linked issue.

Updated CONTRIBUTING to exempt tests from linked issues

---

ipv8/REST/attestation_endpoint.py
ipv8/attestation/communication_manager.py
ipv8/attestation/wallet/database.py
ipv8/database.py

Fixes #982
This PR:
- Removes `database_blob`, which is just an alias for `bytes`.
- Removes `execute_or_script`, which was only needed for MacOS <= Python 3.6.
- Removes `import pysqlite2.dbapi2 as sqlite3`, which was only needed for MacOS <= Python 3.6.

Removed old database.py workarounds

---

doc/basics/identity_tutorial.rst
doc/basics/overlay_tutorial.rst
doc/basics/testbase_tutorial.rst
doc/deprecated/attestation_tutorial.rst
doc/preliminaries/install_libsodium.rst

Fixes #1017
This PR:
- Fixes code blocks with `none` or no language specified not rendering on ReadTheDocs.

Fixed ReadTheDocs unrendered code-blocks

---

ipv8/REST/identity_endpoint.py

If `IdentityEndpoint`'s  `initialize` method was not called prior to shutting down IPv8, it will crash on calling `on_shutdown` callback trying to reference `shutdown()` method of `self.communication_manager` which is `None`.
This little change fixes that, helping with IPv8 testing.

Fixed crashing unitialized endpoint on shutdown

---

doc/index.rst
doc/reference/bootstrapping.rst
doc/reference/configuration.rst
ipv8/loader.py

Fixes #976
This PR:
- Adds bootstrapping documentation.
- Fixes the configuration documentation to include the bootstrapping configuration key.
- Fixes the configuration documentation to accurately list what overlays are loaded by default.
- Fixes the `loader.py` `bootstrapper` docstring.

Added bootstrapping documentation

---

ipv8/messaging/lazy_payload.py
ipv8/test/base.py
ipv8/test/messaging/test_lazy_payload.py

Fixes #989
This PR:
- Adds `__match_args__` to `VariablePayload` to allow for Python 3.10 structural pattern matching.
- Fixes `asynctest.helpers.exhaust_callbacks` no longer working in Python 3.10.
Notes:
- The `exec(compile(...))` construction in `test_lazy_payload.py` exists because Python crashes when importing files with syntax errors. This means that everyone running the tests with a Python version lower than 3.10 would crash when importing this file. As an aside: Python 3.9 has soft keywords for this, but we have to deal with Python 3.7 and Python 3.8 as well.
- This makes IPv8 Python 3.10 compatible.

Added Payload match support

---

doc/simulation/simulation_tutorial_2.py
ipv8/test/mocking/endpoint.py

Fixes #1024
This PR:
- Fixes `AddressTester` using `_address_is_lan_without_netifaces` instead of `address_is_lan`, like the `Community`.
- Fixes `AddressTester.is_lan` always returning False.
- Updates `AddressTester` to be a singleton.
- Updates `simulation_tutorial_2.py` to set the `my_estimated_wan` for its overlays.

Fixed AddressTester using different LAN check

---

doc/basics/discoverystrategy_tutorial.rst
doc/basics/discoverystrategy_tutorial_1.py
doc/basics/discoverystrategy_tutorial_2.py
doc/basics/tasks_tutorial.rst
doc/basics/tasks_tutorial_1.py
doc/basics/tasks_tutorial_2.py
doc/basics/tasks_tutorial_3.py
doc/basics/tasks_tutorial_4.py
doc/basics/tasks_tutorial_5.py
doc/basics/tasks_tutorial_6.py
doc/basics/tasks_tutorial_7.py
doc/index.rst

Fixes #977
This PR:
- Adds a tutorial on task management.
- Adds a tutorial on `DiscoveryStrategy` creation.
These are the basics required to take #979 off of "on hold".

Added tasks tutorial

---

doc/basics/overlay_tutorial.rst
doc/conf.py
doc/index.rst

Fixes #1030
Fixes #1032
This PR:
- Adds `autoapi` API reference documentation generation.
- Adds a warning not to use `Peer.address` to the overlay tutorial documentation.
- Updates the documentation theme from `alabaster` to `sphinx_rtd_theme` for readability.
The warning looks as follows:
The new module index looks like this (zoomed out, we have a sizable number of classes in IPv8):

Added API documentation generation

---

.readthedocs.yaml
doc/requirements.txt

Fixes #1034 (probably - there is no way to test this 😃)
This PR:
- Adds a ReadTheDocs V2 config file.
- Adds a `requirements.txt` for the documentation.

Added ReadTheDocs config file

---

doc/reference/configuration.rst
ipv8/configuration.py
ipv8/test/test_configuration.py
ipv8_service.py

Fixes #1037
Fixes #1038
This PR:
- Adds the option to configure keys with raw private key material (in b64 format).
- Updates the configuration documentation to have a section for the key format.
- Removes ancient (and ugly!) key loading practices.

Added option to configure IPv8 with raw private key material

---

README.md
doc/basics/discoverystrategy_tutorial.rst
doc/basics/identity_tutorial.rst
doc/basics/requestcache_tutorial.rst
doc/basics/tasks_tutorial.rst
doc/basics/testbase_tutorial.rst
doc/deprecated/attestation_tutorial.rst
doc/further-reading/advanced_identity.rst
doc/reference/bootstrapping.rst
doc/reference/configuration.rst
doc/reference/serialization.rst

Fixes #1041
This PR:
- Updates the relative links in the documentation (`doc` directory) to use the new ReadTheDocs format.
- Updates the absolute links in `README.md` to use the new ReadTheDocs format.
New ReadTheDocs behavior example:
https://py-ipv8.readthedocs.io/en/basics/overlay_tutorial
is now
https://py-ipv8.readthedocs.io/en/latest/basics/overlay_tutorial.html
This means that all relative links are now only one folder up and have to refer to other pages with `.html`. Therefore:
`../../basics/tasks_tutorial`
is now
`../basics/tasks_tutorial.html`

Fixed readthedocs links

---

doc/reference/configuration.rst
ipv8/configuration.py
ipv8/test/test_configuration.py
ipv8_service.py

Fixes #1036
This PR:
- Adds configurable `DispatcherEndpoint` initialization in `ipv8_service.py`.
- Adds a warning if the old `"address"` and `"port"` configuration is used. Old configurations still work though.
- Updates the `configuration.rst` documentation to showcase the use of `'interfaces'` instead of `"address"` and `"port"`.
- Updates the `configuration.py` to use the new `'interfaces'` configuration.
- Removes some `asserts` (and corresponding tests) from `ConfigBuilder.finalize()` that were too strict or no longer generic enough for `'interfaces'`. For example, it is allowed (but unconventional) to launch IPv8 without any network interfaces at all.
Preview of documentation change:

Updated Endpoint initialization to use 'interfaces' configuration

---

ipv8_service.py

This PR:
- Fixes the deprecated 'address'/'port' fallback mode not auto-filling the old default values.

Fixed deprecated config not having fallbacks

---

ipv8/loader.py
ipv8/test/test_loader.py

This PR:
- Fixes `CommunityLauncher` calling `super()` instead of `super().__init__()`.
- Fixes `StagedCommunityLauncher.finalize()` returning `super()` instead of `super().finalize()`.
- Fixes `TestCommunityLauncher.setUp()` returning `super()` instead of `super().setUp()`.

Fixed `CommunityLauncher` and `test_loader` `super()` usage

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Fixes #1063
This PR:
- Updates the issue template `bug_report` to start with the label `priority: unknown`.
- Updates the issue template `feature_request` to start with the label `priority: unknown`.
- Removes the OS section from the `bug_report` issue template.

Updated issue templates for new tags

---

ipv8/REST/tunnel_endpoint.py

Fixes #1053
This PR:
- Updates the name of `SpeedTestRequest` schema for `speed_test_existing_circuit` to be `SpeedTestExistingCircuitRequest`. 
- Updates the name of `SpeedTestRequest` schema for `speed_test_new_circuit` to be `SpeedTestNewCircuitRequest`.

Fixed duplicate schema in tunnel REST endpoint

---

ipv8/community.py
ipv8/test/test_community.py

Fixes #1061
This PR:
- Adds more informative errors for when `Community.community_id` is not set or set wrong.
- Updates the default `Community.community_id` to be `None`.
Note that `b''` is a valid Community identifier. Therefore, the default had to be changed to detect it not being set.

Updated error when community_id is missing

---

doc/reference/serialization.rst
doc/reference/serialization_4.py
doc/reference/serialization_5.py
doc/reference/serialization_6.py
doc/reference/serialization_7.py

Fixes #978
This PR:
- Adds documentation for the three non-destructive ways to hook in third-party serialization.
- Adds short examples to documentation for nested payloads.
Here's the page printed to PDF (doesn't use RTD theme):
[Message serialization — IPv8 2.8.0 documentation.pdf](https://github.com/Tribler/py-ipv8/files/7698920/Message.serialization.IPv8.2.8.0.documentation.pdf)
New stuff starts from the `Using external serialization options` section.

Added documentation on third-party serialization (and nested payloads)

---

ipv8/community.py
ipv8/test/test_community.py

Fix for downstream report https://github.com/Tribler/tribler/issues/6648
This PR:
- Updates `Community.received_bootstrapped_addresses` to check if the passed `Future` is cancelled.

Fixed bootstrap received addresses callback not checking for cancel

---

ipv8/messaging/anonymization/utils.py

Fixes #1070
This PR:
- Updates the absolute import in `ipv8/messaging/anonymization/utils.py` to be a relative import.

Converted anonymization utils absolute import to relative import

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Fixes #1069
This PR:
- Updates automatic labeling with `priority: unknown` to be `'priority: unknown'`.

Fixed GitHub issue template labels

---

ipv8/messaging/anonymization/tunnel.py
ipv8/test/messaging/anonymization/test_datachecker.py

Fixes #1079
This PR:
- Updates the `DataChecker` to allow uTP packets with extension `3`.
- Updates the log level of `TunnelExitSocket.is_allowed` to warning, matching the level of `TunnelExitSocket.datagram_received`.

Updated exit data rules

---

create_test_coverage_report.py

Fixes #1085
This PR:
- Updates `create_test_coverage_report.py` to support `coverage` versions lower than `5`, between `5` and `6`, and higher than `6`.
Tested with `coverage==5.5` and `coverage==6.3.1`.

Updated support for different coverage versions

---

.pylintrc
ipv8/messaging/interfaces/endpoint.py
ipv8/test/messaging/interfaces/test_endpoint.py

Fixes #1057
This PR:
- Adds `netifaces` as a pylint external package.
- Fixes yielding `Endpoint` `Interface` objects with a netmask of `0.0.0.0`.

Fixed test suite crash with 0.0.0.0 subnet mask

---

ipv8/configuration.py
ipv8/test/test_configuration.py

Fixes #1072
This PR:
- Adds `ConfigBuilder.add_ephemeral_key()` to create keys that only exist in memory (not on disk).
- Fixes `ConfigBuilder.add_key_from_bin()` missing a return type.
Notes:
I did not make the key curve configurable. If we ever need this, we will need to implement it separately.

Added ConfigBuilder ephemeral key shortcut

---

ipv8/messaging/lazy_payload.py

Fixes #1092
This PR:
- Fixes the result type of the `vp_compile` class decorator by declaring it the same as the argument type.

Fixed `vp_compile` decorator having wrong return type

---

simulation/discrete_loop.py

This PR:
- Fixes an issue with the `create_task` method in the discrete event loop. Details: The wrapper inner function in `create_task` in the `DiscreteLoop` is not returning the result of the task. This causes higher-level asyncio routines that depend on this function, such as `gather` and `ensure_future`, to not correctly fire with the right result.

Fixed `create_task` in `DiscreteLoop`

---

.github/workflows/autoprreview.yml

Fixes #1100
This PR:
- Adds a workflow to approve PRs that have been approved by `Tribler/core` members

Added auto PR review

---

ipv8/peerdiscovery/churn.py
ipv8/test/base.py

Fixes #1110
This PR:
- Adds an `__all__` definition for `base.py` to avoid exporting newly added module-level variables.
- Adds `TestBase` support for Python 3.11 using `unittest.IsolatedAsyncioTestCase`.
- Fixes `RandomChurn` using `random.sample` on a `set` (only `list` is supported as of Python 3.11).
See original issue for implementation substantiation. Other notes:
- `TestBase` now inherits from `unittest.IsolatedAsyncioTestCase` for all Python versions `>= 3.8` by default. However, `asynctest` is still supported up to Python 3.10 and `TestBase` subclasses can switch to `asynctest` by setting `__asynctest_compatibility_mode__` to `True`.
- `loop` has a class scope in `asynctest`, an instance scope in `unittest`, and it needs to be retrieved upon invocation (a `property`) for Python …

Added Python 3.11 support

---

ipv8/messaging/anonymization/community.py

Fixes #1117
This PR:
- Fixes the log message for overwriting an existing circuit retry appearing only when no circuit was overwritten.
For consistency, the inline comment was copied from line 331.

Fixed circuit retry log message

---

requirements.txt
setup.py

Fixes #1122
This PR:
- Fixes `setup.py` test extras entry, now included in the `extras_require` dict.
- Updates the `asynctest` requirement to only install for Python 3.7.
- Removes the minimum version for `cryptography` and `libnacl` ([the specified versions are wrong](https://github.com/Tribler/py-ipv8/issues/1084)).
Pip output on Python 3.8 (note that a local install doesn't explicitly state that it ignores `asynctest`):
[requirements install]
```cmd
\py-ipv8> python -m pip install -r requirements.txt --dry-run
Ignoring asynctest: markers 'python_version == "3.7"' don't match your environment
...
```
[local install]
```cmd
\py-ipv8> python -m pip install .[all] --dry-run
...
>> long list of packages that doesn't include asynctest 
...
```

Set conditional markers for asynctest requirement

---

ipv8/peerdiscovery/community.py

Fixes #1129
This PR:
- Fixes Python 3.11 `sample` incompatibility in `PeriodicSimilarity`.

Fixed PeriodicSimilarity sampling from set

---

ipv8/peerdiscovery/network.py
ipv8/test/peerdiscovery/test_network.py

Fixes #1131
This PR:
- Fixes `Network.discover_services()` creating new caches instead of just updating existing ones.
- Removes calls to `Network.reverse_service_lookup.pop()` using peer addresses.

Fix discovery cache creation

---

ipv8_service.py

Fixes #1136
This PR:
- Updates `IPv8` to run `strategy.overlay.get_peers()` in the general exception handler.

Guard against `get_peers()` in the `IPv8` class

---

run_all_tests.py

This PR:
- Fixes the truncation in the verbose output of the unit tests.
To confirm the fix: the `Tests on Linux` now have `600` lines of output and report `[SUCCESS] Ran 600 tests`.

Fixed truncation in verbose test results

---

ipv8/REST/rest_manager.py
ipv8/test/REST/rest_base.py

Fixes #1149
This PR:
- Updates the `MockRestIPv8` to use `Transport` instances based on IPv8's `MockEndpoint` (circumventing real sockets).
Notes:
- Looking at the data, this PR makes the tests **slower** instead of faster: from `608 tests in 5.55 seconds (39.29 seconds total in tests)` to `7.03 seconds (44.46 seconds total in tests)`.

Updated `MockRestIPv8` to not use real socket

---

ipv8/test/base.py

Fixes #1153
This PR:
- Fixes `TestBase` not checking if event loop exists when attempting to access tasks on lockup.
- Updates use of `threading.currentThread()` (deprecated) instead of `threading.current_thread()`.

Fixed TestBase hanging when event loop missing

---

doc/basics/overlay_tutorial.rst
doc/basics/overlay_tutorial_3.py
doc/basics/overlay_tutorial_4.py
doc/basics/overlay_tutorial_5.py

Fixes #1161
This PR:
- Updates `overlay_tutorial.rst` to show the new `PeerObserver` functionality.
- Updates the `overlay_tutorial_*.py` files to fit within the ReadTheDocs page width.

Updated overlay basics doc to use PeerObserver

---

ipv8/bootstrapping/bootstrapper_interface.py
ipv8/bootstrapping/dispersy/bootstrapper.py

This PR:
- Fixes the `ruff` violations in the `bootstrapping` folder.

Solved ruff violations in the bootstrapping folder

---

ipv8/messaging/serialization.py
ipv8/peerdiscovery/churn.py
ipv8/peerdiscovery/community.py
ipv8/peerdiscovery/discovery.py
ipv8/peerdiscovery/payload.py

This PR:
- Fixes a "wrong" type for `Serializable.from_unpack_list`, which was too narrow.
- Fixes the `ruff` violations in the `peerdiscovery` folder.

Fixed ruff violations for peerdiscovery folder

---

ipv8/REST/asyncio_endpoint.py
ipv8/REST/attestation_endpoint.py
ipv8/REST/base_endpoint.py
ipv8/REST/dht_endpoint.py
ipv8/REST/identity_endpoint.py
ipv8/REST/isolation_endpoint.py
ipv8/REST/network_endpoint.py
ipv8/REST/overlays_endpoint.py
ipv8/REST/rest_manager.py
ipv8/REST/root_endpoint.py
ipv8/REST/schema.py
ipv8/REST/tunnel_endpoint.py
ipv8/peer.py
ipv8/peerdiscovery/churn.py
ipv8/peerdiscovery/community.py
ipv8/peerdiscovery/discovery.py
ipv8_service.py

This PR:
- Fixes the `ruff` violations in the `REST` folder.
- Fixes the `ruff` violations in `peer.py` (touched due to the previous bullet point).
- Fixes incorrect types in the `peerdiscovery` folder.
- Removes the `TransactionSchema` and `BlockSchema` JSON schemas, relating to `TrustChain` (which was moved away from the IPv8 codebase 3 years ago 😃).
- Updates `DiscoveryStrategy` and `IPv8` to explicitly deal with strategies without overlays.

Fixed ruff violations for REST folder

---

doc/basics/requestcache_tutorial.rst
doc/basics/tasks_tutorial.rst
doc/basics/tasks_tutorial_3.py
doc/basics/tasks_tutorial_4.py
doc/basics/tasks_tutorial_5.py
doc/further-reading/advanced_identity.rst
stresstest/peer_discovery_defaults.py

After merging https://github.com/Tribler/py-ipv8/pull/1154 some of the line numbers in the docs were off. This PR fixes this.

Fixed line numbers in docs

---

doc/further-reading/anonymization.rst
ipv8/configuration.py
ipv8/test/test_configuration.py
scripts/exitnode_ipv8_only_plugin.py
scripts/ipv8_plugin.py
scripts/tracker_plugin.py
scripts/tracker_reporter_plugin.py
scripts/tracker_service.py

This PR:
- Fixes the remaining `ruff` violations in the `scripts` folder.
- Updates references to `max_relays_or_exits` by replacing them with the appropriate `max_joined_circuits` (fix ported from #1144).

Fixed ruff violations for the scripts folder

---

ipv8/attestation/wallet/irmaexact/__init__.py
ipv8/attestation/wallet/irmaexact/algorithm.py
ipv8/attestation/wallet/irmaexact/gabi/attributes.py
ipv8/attestation/wallet/irmaexact/gabi/builder.py
ipv8/attestation/wallet/irmaexact/gabi/credential.py
ipv8/attestation/wallet/irmaexact/gabi/keys.py
ipv8/attestation/wallet/irmaexact/gabi/proofs.py
ipv8/attestation/wallet/irmaexact/wrappers.py

This PR:
- Fixes the `ruff` issues in the `ipv8/attestation/wallet/irmaexact` folder.
This folder had the vast majority of violations so I'm separating it from the other `ipv8/attestation` fixes. However, some files will need to be revisited after the API's they implement are typed.

Fixed ruff violations for the irmaexact folder

---

ipv8/peer.py

This PR:
- Updates the `Peer.mid` to be the `SHA-1` of the public key, not the key (in most cases this would be the same though).

Updated mid to always be the hash of the public key

---

ipv8/messaging/interfaces/lan_addresses/addressprovider.py
ipv8/messaging/interfaces/lan_addresses/interfaces.py
ipv8/overlay.py
ipv8/test/messaging/interfaces/lan_addresses/test_addressprovider.py
ipv8/test/test_community.py

This PR fixes https://github.com/Tribler/py-ipv8/issues/1188 by letting all communities periodically run a LAN discovery task using the threadpool. The `AddressProvider.addresses_ts` tries to avoid concurrent/frequent runs.
Note that blocking is still possible for the first call to `discover_addresses` (e.g., when `EndpointListener.__init__` calls `my_estimated_lan`). Although this may only be a problem when adding communities at runtime (which is what we do in Tribler). Alternatively, we could remove the first 2 lines from `get_addresses_buffered` and be unaware of our LAN address until one of the discovery tasks completes.
I removed `verbose` kwarg in interfaces.py because with this PR we can't use `lru_cache(maxsize=2)` anymore. Allowing the cache to be larger than 1 means we don't …

Updated LAN discovery to run on a different thread

---

.ruff.toml
ipv8/REST/attestation_endpoint.py
ipv8/attestation/communication_manager.py
ipv8/attestation/identity/community.py
ipv8/attestation/identity/manager.py
ipv8/attestation/tokentree/token.py
ipv8/attestation/wallet/caches.py
ipv8/attestation/wallet/community.py
ipv8/attestation/wallet/irmaexact/gabi/builder.py
ipv8/attestation/wallet/irmaexact/gabi/keys.py
ipv8/attestation/wallet/primitives/boneh.py
ipv8/attestation/wallet/primitives/structs.py
ipv8/community.py
ipv8/dht/community.py
ipv8/dht/discovery.py
ipv8/dht/storage.py
ipv8/messaging/anonymization/caches.py
ipv8/messaging/anonymization/community.py
ipv8/messaging/anonymization/pex.py
ipv8/messaging/anonymization/tunnel.py
ipv8/messaging/anonymization/utils.py
ipv8/messaging/interfaces/lan_addresses/windows/GetAdaptersAddresses.py
ipv8/peerdiscovery/churn.py
ipv8/peerdiscovery/community.py
ipv8/peerdiscovery/discovery.py
ipv8/peerdiscovery/payload.py
ipv8/taskmanager.py
ipv8/test/test_community.py

Related to #1175
This PR:
- Updates the `ruff` exceptions to ignore `pandas` related errors.
- Updates the `ruff` rules to allow 6 arguments in calls (functions/methods).

Updated the ruff rules to allow more args and ignore pandas violations

---

ipv8/messaging/anonymization/caches.py
ipv8/messaging/anonymization/community.py
ipv8/messaging/anonymization/hidden_services.py
ipv8/requestcache.py
ipv8/test/test_requestcache.py
scripts/tracker_service.py
stresstest/bootstrap_introductions.py
stresstest/bootstrap_rtt.py

Related to #1175
This PR:
- Adds overloaded versions of `RequestCache`'s `.add()`, `.get()`, and `pop()` that return the given class type.
- Updates the simple cases where this new functionality can be used.
- Removes all of the superfluous `typing.cast()` calls where the code was updated.
Pro:
- We don't have to cast everywhere.
Con:
- We have to mix-in `CacheWithName` for all caches that have a name. Thanks @xoriole for suggesting the `NumberCacheWithName` and `RandomNumberCacheWithName` shortcuts.
Ideally, I would've like to have `CacheTypeVar` bound to `NumberCache` and to implement the `CacheWithName` protocol. This is a construction that the `PyCharm` type checker recognizes but `mypy` unfortunately doesn't.

Added typed request cache add/get/pop

---

ipv8/messaging/anonymization/hidden_services.py
ipv8/peerdiscovery/churn.py
ipv8/peerdiscovery/discovery.py

Related to #1175
This PR:
- Fixes mypy-signalled Python 3.11 incompatibility in `hidden_services.py`.
- Updates `DiscoveryStrategy` to be generic for its `overlay` attribute (avoiding casts to `Overlay`).

Updated DiscoveryStrategy to be a generic of its overlay

---

doc/basics/testbase_tutorial.rst

Fixes #1194
This PR:
- Fixes the referenced line numbers in `testbase_tutorial.rst`.

Fixed example lines in testbase_tutorial

---

ipv8/bootstrapping/bootstrapper_interface.py
ipv8/bootstrapping/dispersy/bootstrapper.py
ipv8/bootstrapping/udpbroadcast/bootstrapper.py
ipv8/community.py
ipv8/peerdiscovery/community.py
ipv8/test/bootstrapping/dispersy/test_bootstrapper.py
ipv8_service.py

This PR is meant to simplify the bootstrapping process and introduces the following changes:
* DNS addresses are resolved on the threadpool.
* `DispersyBootstrapper.initialize`/`UDPBroadcastBootstrapper.initialize` are now defined as async functions, although implementations may still return a `Future`.
* Bootstrappers are no longer removed and re-added from `Community.bootstrappers` as a way of keeping track of which ones are initialized. It uses `Bootstrapper.initialized` instead.

Updated bootstrappers to be less complex

---

.readthedocs.yaml

Fixes #1205
This PR:
- Fixes the missing `build.os` configuration entry after the latest ReadTheDocs update.
- Updates the python version configuration entry to be defined in `build.tools.python` instead of (deprecated) `python.version`.

Fixed ReadTheDocs configuration build.os

---

doc/conf.py
doc/requirements.txt

Fixes #1205 (again)
This PR:
- Fixes requirements in `doc/requirements.txt` to work with `Sphinx==7.1.2`.
- Updates deprecations in `doc/conf.py`.
Locally verified with:
```
astroid==3.0.0
Sphinx==7.1.2
sphinx-autoapi==3.0.0
sphinx-rtd-theme==1.3.0
```
This _should_ now work.

Fixed Sphinx deprecations and dependency versions

---

ipv8/messaging/anonymization/community.py

This PR:
- Updates tunnel removals in `TunnelCommunity.unload()` to no longer wait for their tasks (reverting #1172).

Reverted tunnel awaits introduced in #1172

---

ipv8/messaging/anonymization/hidden_services.py

This PR:
- Updates tunnel removals in `hidden_services.py` to no longer register their tasks (reverting #1172).
Note:
The new (w.r.t. the revert) `_ =` assignment is to convince MyPy that we did not forget an `await` or `register_task()`.

Revert of remove_circuit task register introduced in #1172

---

doc/basics/overlay_tutorial_5.py
doc/basics/testbase_tutorial.rst
doc/basics/testbase_tutorial_2.py
doc/reference/serialization.rst
doc/reference/serialization_1.py
doc/reference/serialization_4.py
doc/reference/serialization_7.py
ipv8/messaging/payload_dataclass.py
ipv8/test/messaging/test_payload_dataclass.py

Related to #1196
This PR:
- Removes the (now-useless) `overwrite_dataclass()` function.

Removed overwrite dataclass construction

---

.github/workflows/pr-comment-validate.yml

Related #1056
```
Error:  .github#L1
a step cannot have both the `uses` and `run` keys
```
See also https://github.com/Tribler/py-ipv8/actions/runs/6492024002
This PR:
- Fixes the PR validate action by separating the `run` and `uses` keys.
Note that this is PR `2/?`, without any guarantees on the upper limit needed to get this running.

Fixed the GitHub validate action

---

.github/workflows/pr-comment-validate.yml

Related to #1056
New error:
```
- uses: actions/setup-python@v4
- with:
python-version: ${{ matrix.version }}
run: python --version
>>
Invalid workflow file: .github/workflows/pr-comment-validate.yml#L18
The workflow is not valid. .github/workflows/pr-comment-validate.yml (Line: 18, Col: 9): Unexpected value 'run' .github/workflows/pr-comment-validate.yml (Line: 16, Col: 9): Required property is missing: uses
```
Previous error:
```
- uses: actions/setup-python@v4
with:
python-version: ${{ matrix.version }}
run: python --version
>>
Error: .github#L1
a step cannot have both the `uses` and `run` keys
```
This PR:
- Fixed previous PR making the `with` of the `uses` a new step instead of the `run` (oops).
Documentation referenced: https://docs.github.com/en/actions/using-jobs/using-a-matrix-fo …

Fixed wrong hypen location in GitHub validate PR action

---

ipv8/peerdiscovery/network.py

Fixes #1220
This PR:
- Fixes some peer updates in `Network` not checking the new size of a cache.

Fixed cache leaks in Network

---

.github/workflows/pr-comment-validate.yml
ipv8/keyvault/private/cryptography25519.py
ipv8/keyvault/private/libnaclkey.py
ipv8/keyvault/public/cryptography25519.py
ipv8/keyvault/public/libnaclkey.py
ipv8/test/keyvault/test_25519fallback.py

Fixes #1224 (fixes Windows, MacOS crashes due to other unknown reasons)
This PR:
- Adds a `python-cryptography`-based fallback for when `libnacl` is not found on the system (notably during our validation's matrix tests).
- Adds a type filter for the issue comment trigger (this should stop the validation being run when comments are deleted).
- Removes `macos-latest` from the validation testing matrix.
I'll create a new issue for MacOS.

Added cryptography-based fallback when NaCL import fails

---

ipv8/messaging/serialization.py
ipv8/test/messaging/test_serialization.py

This PR fixes raw support for `NestedPayload`.

Fixed issue with serializing nested payloads that use raw

---

.github/workflows/pr-comment-validate.yml
doc/index.rst
run_all_tests.py

This PR:
- Adds a fallback to the `"."` directory if `run_all_tests.py` is run from the `""` directory.
- Fixes spelling and grammar instance in index.rst
- Fixes the validation matrix still not using the PR head (this time using [this](https://github.com/actions/checkout/pull/1248/files) solution).
This PR is mainly to test the recent validation Action fixes.

Fixed spelling and grammar instance in index.rst

---

ipv8/messaging/anonymization/payload.py
ipv8/messaging/anonymization/tunnel.py
ipv8/messaging/interfaces/endpoint.py
ipv8/messaging/serialization.py
ipv8/test/REST/test_isolation_endpoint.py
ipv8/test/bootstrapping/dispersy/test_bootstrapper.py
ipv8/test/mocking/endpoint.py
ipv8/test/peerdiscovery/test_community.py
ipv8/test/test_community.py

This PR adds IPv6 support to the `TunnelCommunity` and finally closes https://github.com/Tribler/py-ipv8/issues/615. This change will break compatibility with old versions.
Note that when running the unittests in IPv6 mode, we're skipping the tests for `DiscoveryCommunity`/`DispersyBootstrapper` and the old-style introduction requests, since they can't support IPv6.
Also note that I've changed `Address.pack` to work on all types of addresses (namedtuple or not). The reason behind this is that a lot of addresses are still just regular tuples (e.g., `my_estimated_lan`).

Added IPv6 support to TunnelCommunity

---

.github/workflows/pr-comment-validate.yml
create_test_coverage_report.py
distutils_forwardport.py
github_increment_version.py
ipv8/REST/base_endpoint.py
ipv8/messaging/payload_dataclass.py
ipv8/test/REST/rest_base.py
ipv8/test/REST/test_attestation_endpoint.py
ipv8/test/REST/test_identity_endpoint.py
ipv8/test/REST/test_isolation_endpoint.py
ipv8/test/REST/test_network_endpoint.py
ipv8/test/REST/test_overlays_endpoint.py
ipv8_service.py
requirements.txt
run_all_tests.py
setup.py

Fixes #1231
This PR:
- Adds Python 3.12 support (small fixes described in #1231).
Notes:
- According to `aiohttp` logging, `3.9.0b0` works with Python 3.8 or higher. In my testing, this turned out to be Python 3.11 or higher.
- The `import distutils_forwardport` workaround is required in all files that can serve as a main entrypoint for tests that (indirectly) use `apispec`. Once `apispec` is updated, and no longer uses `distutils`, it should be safe to remove this.
- This PR was tested locally on Python 3.12 for Windows.

Added Python 3.12 support

---

scripts/tracker_service.py

Fixes #1245
This PR:
- Fixes the `EndpointServer`'s `super().__init__` not following the new initialization convention.

Fixed tracker service super args

---

requirements.txt

Fixes #1249
This PR:
- Updates the minimum version of `aiohttp` to be `>=3.9.1` for all non-end-of-life Python versions (Python versions >3.7).

Updated aiohttp version

---

.github/workflows/pr-comment-validate.yml
ipv8/test/mocking/endpoint.py

Fixes #1238
Fixes #1243
This PR:
- Fixes `AutoMockEndpoint._generate_address` generating IPv6 addresses that do not work with our test setup.
- Updates the validation tests to also run tests with IPv6.

Fixed mock IPv6 address generation

---

.github/workflows/pr-comment-validate.yml

Related to #1258 (_probably_ fixes)
This PR:
- Adds a new status check "Cross-env Validation" that triggers after "validate" comments.
Notes:
~~I'll also use this PR to (try and) fix the Jenkins push trigger for PR tests.~~ UPDATE: seems fixed.

Added validation action status checks

---

.github/workflows/pr-comment-validate.yml

Fixes issues reported in #1260
This PR:
- Adds target urls for the validation action.
- Fixes `ls-remote` to use `https://github.com/Tribler/py-ipv8` instead of `origin`, which doesn't exist.
- Fixes a missing newline after the `ls-remote` call.
- Updates the validation action job order to first set pending status and then start testing.

Fixed validation action errors

---

.github/workflows/pr-comment-validate.yml

Fixes the issue reported in #1260
This PR:
- Fixes the `actual_pull_head` env value from job `set_pending_status` not being visible to `set_failure_status` and `set_success_status`.

Fixed empty sha on validate action status setting

---

ipv8/attestation/wallet/primitives/cryptography_wrapper.py
ipv8/configuration.py
ipv8/messaging/anonymization/community.py
ipv8/messaging/anonymization/crypto.py
ipv8/test/messaging/anonymization/test_community.py
ipv8/test/messaging/anonymization/test_hiddenservices.py
ipv8/test/test_configuration.py
ipv8_service.py
scripts/exitnode_ipv8_only_plugin.py

This PR does the following:
* Enables `RustEndpoint` in the IPv8 exit node script. I haven't enabled it for all IPv8 nodes, as I don't think it makes sense since normal nodes will be making calls from within Python anyway (removing any chance of a performance improvement).
* Add the ability for the `TunnelCommunity` to deal with `DispatcherEndpoints`.
* Fixes a potential `KeyError` in `relays_cell` for rendezvous points.
* Fixes an issue with leftover asyncio tasks after `TunnelExitSocket` removal.
I also fixed some issues with the `CommunitySettings`:
* Fixes an issue with incorrect peer flags during the tunnel tests.
* Fixes an issue with properties in `CommunitySettings`.
* Fixes an issue with the  default tunnel settings getting stored in `overlay.settings.settings` instead of in …

Updated IPv8 exit node script to use RustEndpoint

---

ipv8/REST/tunnel_endpoint.py

This PR fixes a number of issues with the tunnel endpoint:
* Fixes an issue with the tunnel settings endpoint raising an exception. Since I also wanted to return the `CommunitySettings` defaults, I had to resort to using `dir`.
* Fixes an issue with the relays missing a direction field.
* Fixes an issue with incorrect swagger docs for the speedtest endpoint.

Fixed tunnel endpoints

---

ipv8/messaging/interfaces/dispatcher/endpoint.py
ipv8/messaging/interfaces/endpoint.py
ipv8/test/messaging/anonymization/test_community.py
ipv8/test/messaging/interfaces/dispatcher/test_endpoint.py
ipv8/test/mocking/ipv8.py
ipv8_service.py

This PR makes the necessary changes for `Endpoint.close` to be optionally async.

Updated Endpoint.close to be optionally async

---

ipv8/messaging/interfaces/lan_addresses/any_os/testnet1.py
ipv8/messaging/interfaces/lan_addresses/unix/ioctl.py

This PR:
- Fixes resource warnings when sockets are left to garbage collection if an `OSError` occurs before closing.
This fix is slightly ugly because the `close()` of an unclosed socket can again error out, leading to a nested `try .. except`.

Fixed possibly unclosed sockets for LAN discovery

---

doc/reference/serialization.rst
ipv8/messaging/payload_dataclass.py
ipv8/messaging/serialization.py
ipv8/test/messaging/test_payload_dataclass.py

Hi all,
In my own code, support for serialization of native `ints` and `bool` came in handy. This might also be beneficial to this project.
This PR:
- Adds serialization of dataclasses with attributes that are lists of native `ints` and `bools`.
- Updated the unit tests to test dataclasses with `List[int]` and `List[bool]`

Added serialization of lists of ints and booleans

---

ipv8/test/messaging/anonymization/mock.py

Fixes #1276
This PR:
- Updates `MockDHTProvider` to inherit from `DHTCommunityProvider`.

Updated the Mock DHT provider to inherit from its intended superclass

---

.github/workflows/pr-comment-validate.yml
.github/workflows/unittests.yml
run_all_tests.py

This PR:
- Updates the `unittests` workflow to use Python 3.12 for Mac.
- Updates `run_all_tests` to explicitly pass a "spawn" context.
- Updates the validation success states to link to `validate_attestation_tutorial, validate_identity_tutorial, validate_documentation`.
The `macos` check will fail on this PR. See https://github.com/qstokkink/py-ipv8/pull/2 for the shadow PR with the same commit.

Fix run_all_tests for Mac

---

ipv8/community.py
ipv8/test/base.py

Fixes #1277
Fixes #1289
This PR:
- Fixes `Community._bootstrap()` to allow infinite (-1) `max_peers`.
- Fixes tests locking up on some machines due to LAN address resolution.

Fixed bootstrap with infinite max_peers

---

.github/actions/coverage/action.yml
.github/workflows/coverage.yml
create_test_coverage_report.py

This PR adds a workflow for generating/uploading code coverage reports using GitHub Actions,  and partially addresses https://github.com/Tribler/py-ipv8/issues/1279.

Added workflow for generating code coverage reports

---

ipv8/messaging/anonymization/community.py
ipv8/messaging/anonymization/hidden_services.py
run_all_tests.py

Currently, peers in the `TunnelCommunity` will suggest extending to peers that just have `PEER_FLAG_RELAY` set, and not `PEER_FLAG_EXIT_BT`. This is meant to remove some of the strain on the exit nodes.
However, the circuit creator will currently only try to extend to the suggested peers. This means that circuit creation can needlessly fail. For instance, it's currently not possible to create a 2-hop circuit in a network that consists only of exit nodes, even if the exit nodes all have `PEER_FLAG_RELAY` set.
This PR addresses this issue by letting the circuit creator extend to non-suggested exit nodes as well.

Fixed relaying to exits

---

.github/workflows/coverage.yml
.github/workflows/unittests.yml

Fixes #1294
This PR:
- Fixes the Mac unit tests not finding `libsodium.dylib`.
- Updates the coverage job to be periodic (with the intent of refreshing a cache).
- Removes cache storage from the unittest job (this was doing very little).

Cache libsodium.dll from the main branch

---

doc/basics/identity_tutorial_integration/main.py
doc/deprecated/attestation_tutorial_integration/main.py
run_all_tests.py

This PR:
- Adds a retry to claim the REST ports of the identity validation scripts.
- Updates the dll import path to be `.` instead of `__file__` for the unit tests.
This allows downstream projects, where `__file__` is not located in `.` to work.

Updated default dll import path to be '.'

---

.github/workflows/coverage.yml

This PR:
- Fixes wrong indentation in `coverage.yml`, introduced in #1299.
The jobs is currently failing with this error:
```
Annotations
1 error
Invalid workflow file: 
.github/workflows/coverage.yml#L52
You have an error in your yaml syntax on line 52
```

Fixed indentation in coverage.yml

---

github_increment_version.py

Fixes #1298
This PR:
- Updates `github_increment_version.py` to only use `git` commands.
Full disclosure: I hate this but it seems to be the only way to avoid juggling GitHub access tokens.
Example output:
```
Title: Automated Version Update
Tag version: 2.14
Release title: IPv8 v2.14.2152 release
Body:
Includes the first 2152 commits (+41 since v2.13) for IPv8, containing:
- Added methods for task retrieval to `TaskManager`
- Added ruff/mypy/unittest workflows
- Added serialization of lists of ints and booleans
- Added validation tests to GitHub Actions
- Added workflow for generating code coverage reports
- Cache libsodium.dll from the main branch
- Fixed bootstrap with infinite max_peers
- Fixed coverage job failures
- Fixed indentation in coverage.yml
- Fixed pending task error in …
```

Made github version increment script fully local

---

.github/workflows/pr-comment-validate.yml

This PR:
- Updates the commit status setting to a separate GitHub secret.

Moved commit status setting to separate secret

---

github_increment_version.py

Fixes #1314
This PR:
- Fixes the `github_increment_version` script deleting the branch it is currently on.

Fixed increment version deleting its current branch

---

ipv8/community.py

Fix community bootstrap

---

.github/workflows/pr-comment-validate.yml
setup.py

Found in #1323
This PR:
- Removes Python 3.14 from the validation testing matrix and advertised versions.
This PR cannot be validated itself, I'll use #1323 for that.

Remove Python 3.14 from supported versions

---

doc/basics/overlay_tutorial_5.py
doc/basics/testbase_tutorial.rst
doc/basics/testbase_tutorial_2.py
doc/reference/serialization.rst
doc/reference/serialization_1.py
doc/reference/serialization_4.py
doc/reference/serialization_7.py
ipv8/messaging/lazy_payload.py
ipv8/messaging/payload_dataclass.py
ipv8/test/messaging/test_lazy_payload.py
ipv8/test/messaging/test_payload_dataclass.py

Fixes #1196
This PR:
- Fixes a change in Python 3.13 `locals()` scoping breaking `vp_compile`.
- Updates dataclass-based payloads to inherit from a base class (to hide the magic). 
The fields are identified by PyCharm again:

Updated dataclass payloads to use a base class

---

doc/further-reading/advanced_identity.rst
doc/further-reading/advanced_identity_1.py
doc/further-reading/advanced_identity_2.py
doc/validate_examples.py

This PR:
- Updates `advanced_identity_1.py` and `advanced_identity_2.py` to stop after 1 second. This is not visible in the docs.
- Updates `doc/validate_examples.py` to kill scripts after 5 seconds, instead of 30 seconds.
Based on the previous PR: from `4m 31s` down to `1m 2s`.

Shortened PR doc validation

---

doc/basics/requestcache_tutorial_1.py
ipv8/requestcache.py
ipv8/test/test_requestcache.py

Fixes #1321
This PR:
- Adds `RequestCache.wait_for` to wait for particular caches to be added.
- Updates `test_requestcache.py` to perform `self.request_cache.shutdown()` on `tearDown` (this is less efficient but it keeps the tests smaller).

Added ability to wait for cache arrival in RequestCache

---

doc/further-reading/dht.rst
doc/further-reading/dht_1.py
doc/index.rst
ipv8/dht/community.py

Fixes #1087
This PR:
- Adds documentation for the `DHTCommunity` and the `DHTDiscoveryCommunity`.
- Fixes a bug in the return value of `DHTCommunity.find()`.

Added documentation for the DHT(Discovery)Community

---

ipv8/REST/tunnel_endpoint.py

Fixes https://github.com/Tribler/py-ipv8/issues/1336.
As part of https://github.com/Tribler/py-ipv8/pull/1335 I accidentally committed `TunnelEndpoint.loop`. Getting the event loop is already happening in the Rust module

Removed TunnelEndpoint.loop

---

ipv8/messaging/interfaces/lan_addresses/any_os/getaddrinfo.py

Related to upstream https://github.com/Tribler/tribler/issues/8686
This PR:
- Fixes an uncaught `UnicodeError` being thrown when `socket.getaddrinfo()` is invoked. This is an unsolved bug in CPython.
It seems like we've developed some unfortunate `mypy` errors, since the last PR. Given the number of errors, I think that's best left to a separate PR.

Fixed uncaught getaddrinfo UnicodeError

---

doc/conf.py
ipv8/REST/rest_manager.py
setup.py

Title: Automated Version Update
Tag version: 3.1
Release title: IPv8 v3.1.2226 release
Body:
Includes the first 2226 commits (+29 since v3.0) for IPv8, containing:
- Fixed circuit creation
- Fixed compatibility with marshmallow 4.0.0
- Fixed error when adding peers to the routing table
- Fixed memory leak in GetIfAddrs
- Fixed uncaught getaddrinfo UnicodeError
- Removed TunnelEndpoint.loop
- Updated CommunityLauncher to be a Generic
- Updated TunnelEndpoint to test circuits in Rust
- Updated minimum Python version to 3.10
- Updated validate job Python version to be 3.10 instead of 3.1
- Updated workflow action version
- Upgrade code base to Python 3.10

Automated version increment

---

ipv8/test/messaging/anonymization/test_hiddenservices.py

All values in `TunnelCommunity.candidates` should be `list`.
This becomes an issue when using `ipv8-rust-tunnels`.

Fixed TestHiddenServices setting bad peer flags
