- run_all_tests_unix.sh
I needed these changes to get this script working on Arch. @qstokkink will this break Ubuntu or Debian?
> Use python and nosetests versions explicitely

- ipv8_service.py
This solves compatibility issues with Tribler.
> Added support for pem file encoding

- test/attestation/trustchain/__init__.py
- test/attestation/trustchain/test_block.py
- test/mocking/ipv8.py
- test_classes_list.txt
Also fixed a few pylint errors
> Added a few tests for a TrustChain block

- ipv8/attestation/trustchain/block.py
- ipv8/attestation/trustchain/caches.py
- ipv8/attestation/trustchain/community.py
- ipv8/attestation/trustchain/database.py
- ipv8/messaging/serialization.py
- test/attestation/trustchain/test_community.py
- test/base.py
- test/mocking/ipv8.py
> Various additions to IPv8

- ipv8/messaging/anonymization/hidden_services.py
- ipv8/messaging/anonymization/tunnel.py
Changes according to integration feedback with Tribler.
> Changes to TunnelCommunity for better integration

- ipv8/peerdiscovery/churn.py
- ipv8/peerdiscovery/discovery.py
> Fixed peers being wrongly dropped

- ipv8/peerdiscovery/discovery.py
> Added RandomWalk window size

- ipv8/peerdiscovery/network.py
- test/peerdiscovery/test_network.py
> Added Network snapshotting

- ipv8/messaging/interfaces/udp/endpoint.py
> Fixed EndpointClosedException initialization

- test/messaging/anonymization/test_hiddenservices.py
I had to debug the e2e circuit when verifying payouts so I decided to move the code I've written to reconstruct the e2e circuit, to the hidden services tests. This should make the hidden services tests more accurate.
> Added verification of e2e circuit length to tests

- ipv8/deprecated/community.py
- ipv8/messaging/anonymization/community.py
Also increased the default TunnelCommunity circuit count
> Fixed peer discovery stopping too early

- ipv8/attestation/trustchain/caches.py
> Don't pop an already popped cache

- REST/attestation_endpoint.py
- ipv8/attestation/identity/community.py
- ipv8/attestation/trustchain/community.py
- ipv8/attestation/wallet/caches.py
- ipv8/attestation/wallet/community.py
- ipv8/configuration.py
Some stuff in the attestation and identity communities broke due to recent changes. This PR fixes this.
> Fixes due to recent TrustChain changes

- REST/attestation_endpoint.py
- ipv8/attestation/wallet/caches.py
- ipv8/attestation/wallet/community.py
- test/attestation/wallet/test_attestation_community.py
Used for local staging and demo-ing
> Various enhancements to attestation community

- README.md
- doc/overlay_tutorial.md
> Created ipv8 overlay tutorial

- ipv8/attestation/trustchain/community.py
> Fix TrustChain.unload() race condition

- ipv8/deprecated/community.py
- ipv8/peerdiscovery/deprecated/discovery.py
- ipv8/peerdiscovery/deprecated/discovery_payload.py
- ipv8/test/peerdiscovery/deprecated/test_discovery.py
> Added backwards compatibility for Discovery intro

- ipv8/attestation/trustchain/caches.py
- ipv8/attestation/trustchain/community.py
- ipv8/test/attestation/trustchain/test_community.py
This avoids IO bombing a node to death in (especially when a node does not know many other peers and nodes keep approaching the same counterparty).
> Added cooldown for intro response crawls

- ipv8/messaging/anonymization/community.py
> Fixed sending destroy for None circuit

- ipv8/test/mocking/community.py
Yet another compatibility fix for the new endpoint code.
> Fix MockCommunity to be compatible with new endpoint

- ipv8/REST/attestation_endpoint.py
- ipv8/attestation/wallet/community.py
- ipv8/attestation/wallet/primitives/attestation.py
This brings down the attestation time from 10 seconds to 0.7 seconds.
> Switched from sha-512 to sha-256 attribute proofing

- ipv8/REST/attestation_endpoint.py
- ipv8/attestation/wallet/community.py
- ipv8/test/attestation/wallet/test_attestation_community.py
This allows clients to add metadata to an attestation request.
Practically this allows users of our attestation community to pass on tokens to their own backends (like external IDs).
> Added metadata to attestation requests

- ipv8/REST/attestation_endpoint.py
Right now it is really annoying to perform a whitewashing attack on our system. This PR adds the ability to easily erase your identity.
This is, of course, only used in testing/demo-ing our solution. If you were to use this in the wild, you would be detected as a cheater.
> Added call to wipe your complete identity

- ipv8/attestation/trustchain/community.py
- ipv8/attestation/trustchain/database.py
- ipv8/test/attestation/trustchain/test_community.py
> Added corrupt chain recovery

- ipv8/attestation/trustchain/community.py
- ipv8/test/attestation/trustchain/test_community.py
Also written a simple test to reproduce this 👍
> Fixed bug when sending crawl responses

- ipv8/REST/attestation_endpoint.py
- ipv8/attestation/wallet/community.py
> Made attestation callback human readable

- ipv8/attestation/trustchain/block.py
- ipv8/test/attestation/trustchain/test_block.py
> Refactored block validation into smaller chunks

- ipv8/messaging/anonymization/hidden_services.py
- ipv8/test/messaging/anonymization/test_hiddenservices.py
Also simplifies logic in `find_download()`.
> Fixed race condition in hiddenservices test

- ipv8/attestation/trustchain/block.py
- ipv8/attestation/trustchain/community.py
- ipv8/test/attestation/trustchain/test_community.py
> Added support for self-signed blocks

- ipv8/database.py
This can cause nasty segfaults.
> Synchronize Database.close

- ipv8/messaging/interfaces/udp/endpoint.py
We tested the impact of this PR on the performance of the endpoint; impact is negligible.
> Keep track of outgoing/incoming bytes in endpoint

- ipv8/deprecated/community.py
> Resolved edge-case network partitioning

- ipv8/REST/attestation_endpoint.py
- ipv8/attestation/identity/community.py
- ipv8/deprecated/community.py
- ipv8/test/attestation/identity/test_identity.py
This PR allows you to advertise the metadata with an attribute in your identity.
> Added metadata to attribute list

- ipv8/peerdiscovery/churn.py
- ipv8/peerdiscovery/discovery.py
Fixes #73 
Adds a lock to each of the walk strategies.
> Added locks to walk strategies

- ipv8/test/messaging/interfaces/udp/test_endpoint.py
> Fixed wrong port sending in tests

- ipv8/deprecated/community.py
This adds a lazy wrapper for unsigned messages.
> Added unsigned lazy wrapper

- ipv8/attestation/trustchain/community.py
Related to https://github.com/Tribler/tribler/issues/3751
> Toned down default crawl response blocks count

- ipv8/deprecated/community.py
- ipv8/deprecated/payload.py
- ipv8/messaging/anonymization/caches.py
- ipv8/messaging/anonymization/community.py
- ipv8/messaging/anonymization/hidden_services.py
- ipv8/messaging/anonymization/payload.py
- ipv8/messaging/anonymization/tunnel.py
- ipv8/peerdiscovery/deprecated/discovery_payload.py
- ipv8/test/messaging/anonymization/test_community.py
- ipv8/test/messaging/anonymization/test_hiddenservices.py
- ipv8/test/mocking/exit_socket.py
- ipv8/test/peerdiscovery/deprecated/test_discovery.py
Note that this PR changes the tunnel protocol, so I've also had to change the community ID.
> READY: Tunnel cleanup

- ipv8/messaging/anonymization/caches.py
Fixes https://github.com/Tribler/py-ipv8/issues/207.
> Fix CircuitRequestCache timeout

- ipv8/attestation/trustchain/block.py
- ipv8/attestation/trustchain/community.py
- ipv8/test/attestation/trustchain/test_community.py
…nds, in addition to their use case.
Fixes #128 .
> Link Block and no initial counterparty Source Block shorthands.

- ipv8/attestation/trustchain/block.py
- ipv8/deprecated/community.py
- ipv8/messaging/anonymization/community.py
- ipv8/messaging/serialization.py
- ipv8/peerdiscovery/deprecated/discovery.py
- ipv8/test/messaging/test_serialization.py
> Fixed threading issue with VarLen serialization

- ipv8/attestation/wallet/community.py
> Fixed hash clash for attestation check

- ipv8/test/messaging/anonymization/test_community.py
> Fixed race condition in tunnel tests

- systemd/ipv8-tracker@.service
- twisted/plugins/tracker_plugin.py
It has been deployed and tested already on hose3 (port 6742).
> Added IPv8 tracker

- ipv8/REST/attestation_endpoint.py
- ipv8/attestation/wallet/community.py
Fixes #165 ,  fixes #225.
This can be merged once we need it.
> Various improvements for the attestation community

- ipv8/REST/attestation_endpoint.py
…moved the indexing in the allow_verify request handler, and removed the deferred reference in the outstanding_verify handler.
> Small changes in the attestation endpoint module

- ipv8/messaging/anonymization/tunnel.py
> Fixed check whether exit packet is IPv8

- ipv8/REST/root_endpoint.py
- ipv8/REST/trustchain_endpoint.py
- ipv8/attestation/trustchain/database.py
The endpoint can be used to query information about available blocks in ones database.
> Added TrustChain endpoint in REST API

- ipv8/REST/overlays_endpoint.py
- ipv8/REST/root_endpoint.py
This will eventually replace the request endpoint `/statistics/communities` in Tribler 👍
> Added overlays endpoint in REST API

- ipv8/attestation/trustchain/community.py
> Also broadcast block when creating it

- ipv8/deprecated/community.py
- ipv8/deprecated/network_stats.py
- ipv8/messaging/interfaces/statistics_endpoint.py
- ipv8/test/mocking/ipv8.py
- ipv8_service.py
> Added community statistics

- ipv8/messaging/interfaces/statistics_endpoint.py
Added missing endpoint listener on statistics endpoint.
> Added missing endpoint listener on statistics endpoint

- ipv8/peerdiscovery/network.py
> Network now depends on naked mid

- ipv8/taskmanager.py
- ipv8/test/test_taskmanager.py
> Allow for anonymous tasks in TaskManager

- ipv8/attestation/wallet/primitives/attestation.py
- ipv8/attestation/wallet/primitives/cryptosystem/boneh.py
- ipv8/attestation/wallet/primitives/cryptosystem/ec.py
- ipv8/attestation/wallet/primitives/cryptosystem/value.py
- ipv8/attestation/wallet/primitives/structs.py
- ipv8/test/attestation/wallet/primitives/cryptosystem/test_boneh.py
- ipv8/test/attestation/wallet/primitives/cryptosystem/test_ec.py
- ipv8/test/attestation/wallet/primitives/cryptosystem/test_value.py
- ipv8/test/attestation/wallet/primitives/test_attestation.py
- ipv8/test/attestation/wallet/primitives/test_structs.py
> Made wallet primitives PEP8 and Python 3 compliant

- ipv8/attestation/trustchain/community.py
> Fixed deadlock in TrustChain tests

- ipv8/attestation/wallet/caches.py
- ipv8/attestation/wallet/community.py
- ipv8/attestation/wallet/database.py
- ipv8/attestation/wallet/payload.py
- ipv8/attestation/wallet/primitives/attestation.py
- ipv8/attestation/wallet/primitives/cryptosystem/boneh.py
- ipv8/attestation/wallet/primitives/cryptosystem/cryptography_wrapper.py
- ipv8/attestation/wallet/primitives/cryptosystem/ec.py
- ipv8/attestation/wallet/primitives/cryptosystem/value.py
- ipv8/attestation/wallet/primitives/structs.py
- ipv8/database.py
- ipv8/test/attestation/wallet/primitives/cryptosystem/test_boneh.py
- ipv8/test/attestation/wallet/primitives/cryptosystem/test_ec.py
- ipv8/test/attestation/wallet/primitives/cryptosystem/test_value.py
- ipv8/test/attestation/wallet/primitives/test_attestation.py
- ipv8/test/attestation/wallet/primitives/test_structs.py
- ipv8/test/attestation/wallet/test_attestation_community.py
Related to #265 
This completes all of the Python 3 static analysis issues with the `attestation/wallet` directory.
> Finished attestation wallet Python 3 compatibility

- ipv8/deprecated/community.py
- ipv8/messaging/anonymization/community.py
- ipv8/messaging/anonymization/hidden_services.py
- ipv8/messaging/anonymization/tunnelcrypto.py
- ipv8/messaging/deprecated/encoding.py
- ipv8/messaging/interfaces/endpoint.py
- ipv8/messaging/interfaces/statistics_endpoint.py
- ipv8/requestcache.py
- ipv8/util.py
> Ported several classes to Python 3

- ipv8/REST/attestation_endpoint.py
- ipv8/REST/trustchain_endpoint.py
- ipv8/database.py
- ipv8/dht/community.py
- ipv8/dht/discovery.py
- ipv8/dht/provider.py
- ipv8/dht/routing.py
- ipv8/dht/trie.py
- ipv8/peer.py
- ipv8/util.py
> Ported several more classes to Python 3

- ipv8_service.py
This fixes compatibility with Tribler.
> Fixed imports in ipv8_service

- ipv8/REST/attestation_endpoint.py
- ipv8/REST/dht_endpoint.py
- ipv8/REST/overlays_endpoint.py
- ipv8/dht/routing.py
- ipv8/test/dht/test_routing.py
- ipv8/test/peerdiscovery/test_network.py
- ipv8/test/test_peer.py
Related to #265.
This is the penultimate PR for the Python 3 port. The only remaining files to port are for TrustChain.
> Ported even more classes to Python 3

- ipv8_service.py
> Fixed import structure of IPv8 service

- ipv8/messaging/anonymization/community.py
- ipv8/test/messaging/deprecated/test_encoding.py
> Fixed PingPayload deserialization

- ipv8/REST/overlays_endpoint.py
- ipv8/attestation/trustchain/community.py
- ipv8/deprecated/lazy_community.py
- ipv8/messaging/interfaces/statistics_endpoint.py
Enhancements for better tooling and measurements
- Added statistics REST endpoint to get aggregate (community level) and detailed (message level) statistics
- Added functools.wraps to get better name of decorated functions
This is currently WIP and will accompany a separate PR in Tribler.
> Enhancements for better tooling and measurements

- ipv8/attestation/trustchain/block.py
- ipv8/attestation/trustchain/payload.py
- ipv8/messaging/deprecated/encoding.py
- ipv8/test/attestation/trustchain/test_block.py
- ipv8/test/attestation/trustchain/test_community.py
> Optimized TrustChain packing

- ipv8/REST/overlays_endpoint.py
- ipv8/messaging/interfaces/statistics_endpoint.py
Related to https://github.com/Tribler/tribler/issues/3919
> Fixed StatisticsEndpoint

- ipv8_service.py
> Allow for ipv8_service in twistd

- ipv8/deprecated/community.py
- twisted/plugins/tracker_plugin.py
Fixes:
- Superfluous comma.
- `on_introduction_response` passing unused `data`.
- Tracker plugin not NAT puncturing correctly.
> Various community/tracker fixes

- doc/attestation_tutorial.md
- ipv8/REST/attestation_endpoint.py
Also fixes some unexpected REST API functionality.
Fixes #324.
> Added attestation tutorial

- doc/attestation_tutorial.md
> Updated attestation tutorial

- ipv8_service.py
> Wrapped take_step in try except

- ipv8/test/test_taskmanager.py
This is no longer needed now that we use Twisted's trial.
> Removed obsolete untwisted wrapper

- ipv8/attestation/trustchain/caches.py
- ipv8/attestation/trustchain/community.py
This PR adds retransmission of blocks for sign requests on timeout.
Fixes #314.
> Added TrustChain sign request retransmit

- ipv8/attestation/trustchain/block.py
- ipv8/test/attestation/trustchain/test_block.py
Also fixed bug with duplicate `hash` field in iterator
> Added TrustChain block tests

- ipv8/taskmanager.py
- ipv8/test/test_taskmanager.py
Also fixed Python3 bug with TaskManager cleanup
> Added TaskManager tests

- ipv8/requestcache.py
- ipv8/test/base.py
- ipv8/test/test_requestcache.py
> Added requestcache tests

- stresstest/bootstrap_rtt.py
This produces output compatible with the old Dispersy bootstrap test.
Previously `https://jenkins-ci.tribler.org/job/Test_BootstrapServers/lastSuccessfulBuild/artifact/summary.txt/*view*/`, new:
```
HOST_NAME ADDRESS REQUESTS RESPONSES
dispersy1.st.tudelft.nl 130.161.119.206:6421 10 10
dispersy2.st.tudelft.nl 130.161.119.206:6422 10 10
* 131.180.27.161:6427 10 10
dispersy7.tribler.org 95.211.155.142:6427 10 10
dispersy8.tribler.org 95.211.155.131:6428 10 10
dispersy4.tribler.org 83.149.70.6:6424 10 10
dispersy3.st.tudelft.nl 131.180.27.155:6423 10 10
```
Previously `https://jenkins-ci.tribler.org/job/Test_BootstrapServers/lastSuccessfulBuild/artifact/walk_rtts.txt/*view*/`, new:
```
HOST_NAME ADDRESS RTT
dispersy1.st.tudelft.nl 130.161.119.206:6421 0.016950
dispersy1.st.tudelft.nl …
```
> Added bootstrap ping stresstest

- test_classes_list.txt
> Fixed test coverage report

- ipv8/REST/attestation_endpoint.py
- ipv8/messaging/anonymization/tunnel.py
> Various fixes

- ipv8/overlay.py
- ipv8/peerdiscovery/community.py
- ipv8/peerdiscovery/payload.py
- ipv8/test/mocking/community.py
- ipv8/test/peerdiscovery/test_community.py
- ipv8_service.py
- test_classes_list.txt
- twisted/plugins/tracker_plugin.py
> Added custom strategy declaration

- ipv8/attestation/trustchain/caches.py
> Fixed refreshing TrustChain cache before popping

- ipv8/attestation/identity/community.py
Also fixed multiple inheritance init
> Changed IdentityCommunity identifier

- ipv8/test/mocking/rest/base.py
Also fixed spelling error
Probably fixes #364.
> Fixed socket reserving in REST tests

- doc/overlay_tutorial.md
- ipv8_service.py
> Allow custom community map in IPv8

- ipv8/REST/attestation_endpoint.py
Fixes #375, as described in the issue.
> Fixed attribute flip flopping in REST ep

- ipv8/attestation/trustchain/community.py
- ipv8/dht/community.py
- ipv8/messaging/anonymization/community.py
Fixes #383
There were only a few cases (left) where `Deferred.addCallback` was used inappropriately. This PR fixes those.
> Added default errbacks where appropriate

- ipv8/attestation/identity/community.py
> Made IdentityCommunity use separate DB

- ipv8/dht/community.py
- ipv8/dht/discovery.py
- ipv8/peerdiscovery/churn.py
- ipv8/test/dht/test_community.py
- ipv8/test/peerdiscovery/test_churn.py
- test_classes_list.txt
This is an implementation of the enhancement suggested in #273.
> DHT looping call churn

- ipv8_service.py
> Fixed Python 3 always using LibNaCL keys

- setup.py
Fixes #393
Required for pip release.
> Updated version to 1.4

- setup.py
> Fixed a bug in the setup.py, where the main service class was not included

- doc/crawler_service_tutorial.md
A short Trustchain crawler setup from scratch tutorial
> A short Trustchain crawler setup from scratch tutorial

- ipv8/peerdiscovery/discovery.py
This lead to very slow introduction times.
> Fix reset probability being inverted

- README.md
> Use hard links in README.md

- setup.py
@qstokkink Can you update the pip package? The current version throws errors all over the place because of the invalid packet byte length
Closes #414
> Updated the version to 1.5.0

- ipv8/messaging/interfaces/udp/endpoint.py
> Fix race condition with sending packets

- setup.py
> Added classifiers

- ipv8/messaging/anonymization/hidden_services.py
Fixes https://github.com/Tribler/py-ipv8/issues/420.
> Fix key error

- ipv8/REST/overlays_endpoint.py
Fixed unknown message statistics
> Fixed unknown message statistics

- ipv8/attestation/trustchain/community.py
- ipv8/overlay.py
Removed bias toward trusted nodes in TrustChain. Also removed `get_trust` from `Overlay`.
> Removed biased walking from TrustChain

- ipv8/messaging/payload.py
- ipv8/messaging/serialization.py
> Removed is_list_descriptor

- ipv8/community.py
- ipv8/overlay.py
- ipv8/peerdiscovery/churn.py
- ipv8/peerdiscovery/community.py
- ipv8/peerdiscovery/discovery.py
- ipv8/test/mocking/discovery.py
- ipv8/test/mocking/rest/ipv8.py
- ipv8_service.py
- stresstest/endpoint_stresstest.py
- twisted/plugins/tracker_plugin.py
Fixes #444
Also replaced some old-style `master_peer.key.key_to_hash()` instances with `master_peer.mid`.
> Removed unused service_id usage

- ipv8/REST/dht_endpoint.py
Fixes https://github.com/Tribler/tribler/issues/4227
> Fixed DHTEndpoint unhooked callbacks

- ipv8/REST/attestation_endpoint.py
- ipv8/REST/base_endpoint.py
- ipv8/REST/dht_endpoint.py
- ipv8/REST/network_endpoint.py
- ipv8/REST/overlays_endpoint.py
- ipv8/REST/rest_manager.py
- ipv8/REST/root_endpoint.py
- ipv8/REST/trustchain_endpoint.py
- ipv8/REST/tunnel_endpoint.py
Moved CORS header to be included in every request
Added new base class for all API endpoints
All endpoints now have the HTTP OPTIONS method
All endpoints now have CORS preflight functionality
Renamed method in network endpoint because it was interfering with Twisted naming convention, causing it to show up in the allowed HTTP methods
> Added new endpoint base class with OPTIONS method and CORS preflight functionality

- ipv8/REST/tunnel_endpoint.py
- ipv8/gossip/community.py
- ipv8/messaging/anonymization/caches.py
- ipv8/messaging/anonymization/community.py
- ipv8/messaging/anonymization/tunnel.py
- ipv8/requestcache.py
- ipv8/test/gossip/test_community.py
- ipv8/test/messaging/anonymization/test_community.py
- test_classes_list.txt
Further development of PR #186.
> Gossip Overlay 

- ipv8/REST/attestation_endpoint.py
- ipv8/test/REST/attestationendpoint/test_attestation_endpoint.py
> Fix attestations being reported as attributes by REST API

- ipv8/REST/dht_endpoint.py
- ipv8/test/REST/dht/test_dht_endpoint.py
This PR attempts to address one of the improvements to the DHT flagged in issue #451.  When a new TC block is created it will automatically be published to the DHT (by the peer which owns the block) using a mechanism which will attempt to publish each chunk of the block individually, only moving to the next chunk of the block when the previous chunk was successfully published. If a chunk for whatever reason cannot be published, the current implementation will seek to retry to publish the chunk. There is a limited number of retries per chunk (currently 3), thus after that many tries, no more attempts will be made, and the block will not be published completely. More specifically, the current code will not try to publish the next chunks in the block at all.  As a side effect of this, a …
> Retry mechanism for new TC block publishing to DHT

- ipv8/messaging/interfaces/endpoint.py
This removes the hard requirement for netifaces.
> Removed netifaces requirement

- README.md
- doc/crawler_service_tutorial.md
- doc/install_libsodium.md
> Extract libsodium installation tutorial and add it to README.md

- github_increment_version.py
I am open to file name change requests.
> Added automatic setup.py version incrementer

- ipv8/REST/dht_endpoint.py
- ipv8/test/REST/dht/test_dht_endpoint.py
This PR addresses part of issue #451. The latest stored TrustChain block in the local TrustChain database will be automatically republished to the DHT by the node which owns it. A block that is stored in the local TrustChain database should already have been published as soon as the block was added to the database, so the newly added mechanism should just republish it periodically. Currently, the refresh is done on an hourly basis. The chunks will not be duplicated if they are already stored in the DHT. 
To enable the periodical refresh, a `LoopingCall` in the `DHTBlockEndpoint`, which is attached to the peer's `TrustChainCommunity`'s `TaskManager` object, schedules the `publish_latest_block` every hour. This method implements the refresh. When a new block is added, the `LoopingCall` is …
> Automatic DHT entry republishing for the latest stored TrustChain block chunks

- github_increment_version.py
The result is shown here: #505
> Added automatic release bumper

- ipv8/attestation/trustchain/caches.py
- ipv8/attestation/trustchain/community.py
This Deferred is called when the crawler finishes with the crawl. It can be used as notification for other components to perform a specific action when a crawl has finished.
> Added Deferred return value to crawl_chain method

- ipv8/attestation/identity/community.py
- ipv8/attestation/trustchain/community.py
The `should_sign` currently returns a boolean value, indicating whether we should sign an incoming block or not. However, it is possible that some asynchronous operation needs to happen before we can determine whether an incoming block should be signed (e.g., fetching some network data). To allow for this use-case, I slightly refactored the `should_sign` method in the `TrustChainCommunity`, such that it can deal with listeners that are returning a `Deferred` in the should_sign method.
The method is fully backwards compatible with the existing implementations of `should_sign`.
> Made should_sign method asynchronous

- ipv8/attestation/trustchain/community.py
- ipv8/test/attestation/trustchain/test_community.py
Our current TrustChain crawling depends on introduction requests that contain an integer with the chain length. However, we cannot always assume that the length of the chain is known when invoking `crawl_chain`. Therefore, if the `latest_block_num` argument is `None` and there is no information about the crawled peer in the database so far, we should first send out a request to fetch the latest block of that peer. By doing so, we find out the chain length and proceed with the crawl.
> Crawling now works without knowing chain length

- github_increment_version.py
> Fixed version incrementer one-off

- ipv8/attestation/trustchain/block.py
- ipv8/attestation/trustchain/community.py
- ipv8/attestation/trustchain/database.py
> Fixed block type loading from database

- ipv8/peer.py
- ipv8/peerdiscovery/churn.py
- ipv8/peerdiscovery/community.py
- ipv8/test/test_peer.py
> Added ping measurements for peers

- ipv8/peer.py
- ipv8/test/test_peer.py
> Fixed peer ping median calculation

- ipv8_service.py
Also fixes division bug: the smoothing value was always 0 due to the integer division.
> Fixed sleeping on main thread in event loop

- ipv8/REST/dht_endpoint.py
> READY: Fixed references to failure.value.message

- ipv8/attestation/trustchain/block.py
> Added convenience struct for TrustChainBlock creation

- ipv8_service.py
This was a side effect of #552
> Fix loop cancel in strategy LoopingCall

- ipv8/attestation/trustchain/community.py
> Wrapping result of should_sign in maybeDeferred

- ipv8/messaging/anonymization/community.py
> Fixed error when pinging in tunnel community

- ipv8/peerdiscovery/network.py
- ipv8/test/peerdiscovery/test_network.py
This PR contains optimization of some `Network` methods and also changes `Community` behavior to respond to already known peers upon receiving an introduction request.
> Network optimizations

- ipv8/attestation/trustchain/blockcache.py
> Fixed blockcache using unwritable buffer name

- ipv8/peerdiscovery/network.py
- ipv8/test/peerdiscovery/test_network.py
> Fixed service cache not checking for verified peers

- ipv8/community.py
> Added support for trackers on same subnet

- ipv8/attestation/trustchain/block.py
- ipv8/messaging/deprecated/encoding.py
> Added utf-8 decoding for deprecated custom encoding

- ipv8/community.py
- twisted/plugins/tracker_plugin.py
> Fix puncture without DiscoveryCommunity

- README.md
- doc/basics/attestation_tutorial.rst
- doc/basics/crawler_service_tutorial.rst
- doc/index.rst
It seems my previous PR broke all of the links in the documentation.
> Fixed links in docs

- doc/index.rst
- doc/reference/serialization.rst
This adds some documentation explaining how the IPv8 serialization works.
> Added serialization documentation

- README.md
- doc/further-reading/trustchain.rst
- doc/reference/configuration.rst
- doc/reference/serialization.rst
Addresses https://github.com/Tribler/py-ipv8/pull/609#discussion_r344178264
> Minor fixes to documentation

- ipv8/attestation/wallet/irmaexact/__init__.py
- ipv8/attestation/wallet/irmaexact/enroll_script.py
- ipv8/attestation/wallet/irmaexact/gabi/builder.py
- ipv8/attestation/wallet/irmaexact/gabi/credential.py
- ipv8/attestation/wallet/irmaexact/gabi/keys.py
> Eliminated use of random.randint for IRMA

- ipv8/REST/attestation_endpoint.py
- ipv8/REST/dht_endpoint.py
- ipv8/REST/isolation_endpoint.py
- ipv8/REST/network_endpoint.py
- ipv8/REST/noblock_dht_endpoint.py
- ipv8/REST/overlays_endpoint.py
- ipv8/REST/rest_manager.py
- ipv8/REST/schema.py
- ipv8/REST/trustchain_endpoint.py
- ipv8/REST/tunnel_endpoint.py
- ipv8/community.py
- ipv8/test/REST/attestationendpoint/test_attestation_endpoint.py
- ipv8/test/mocking/rest/peer_interactive_behavior.py
- requirements.txt
- setup.py
> Added swagger docs

- scripts/trustchain_crawler_plugin.py
> Fixed trustchain crawler lambda

- ipv8/test/peerdiscovery/test_community.py
> Fixed bootstrap test wrong assertion

- ipv8/test/attestation/wallet/irmaexact/test_builder.py
> Fix IRMA build_proofs test

- ipv8/test/attestation/wallet/irmaexact/test_builder.py
> Fix irma test asyncio

- requirements.txt
- setup.py
> Updated project requirements

- doc/further-reading/trustchain.rst
Written a small overview section that describes the key concepts of TrustChain such as half blocks and the individual ledger.
Fixes #401
> Clarified half blocks in TrustChain documentation

- ipv8/peer.py
- ipv8/test/test_peer.py
> Fixed peer inequality check in Python 2.7 

- ipv8/REST/dht_endpoint.py
- ipv8/REST/isolation_endpoint.py
- ipv8/REST/noblock_dht_endpoint.py
- ipv8/attestation/trustchain/block.py
- ipv8/attestation/trustchain/community.py
- ipv8/attestation/wallet/primitives/boneh.py
- ipv8/community.py
- ipv8/dht/provider.py
- ipv8/keyvault/crypto.py
- ipv8/messaging/anonymization/caches.py
- ipv8/messaging/anonymization/community.py
- ipv8/messaging/anonymization/hidden_services.py
- ipv8/messaging/anonymization/payload.py
- ipv8/messaging/anonymization/tunnel.py
- ipv8/test/attestation/trustchain/test_community.py
- ipv8_service.py
- scripts/tracker_plugin.py
- stresstest/bootstrap_rtt.py
- stresstest/endpoint_stresstest.py
Fixes #650 . Changes the exceptions according to what was specified in #650 . In addition, changed a few %-formatted strings to f-strings and removed a few redundant u-prefix from some strings.
> Change bare exceptions.

- ipv8/REST/attestation_endpoint.py
- ipv8/REST/network_endpoint.py
- ipv8/peerdiscovery/community.py
- ipv8/peerdiscovery/network.py
- ipv8/test/attestation/trustchain/test_community.py
- scripts/tracker_plugin.py
> Switched verified_peers to set datastructure

- doc/basics/attestation_tutorial.rst
- doc/basics/crawler_service_tutorial.rst
- doc/further-reading/trustchain.rst
- doc/reference/serialization.rst
> Fixed readthedocs links

- ipv8/peerdiscovery/discovery.py
> Filter peers by community in RandomWalk strategy

- requirements.txt
- run_all_tests_unix.sh
- run_all_tests_windows.bat
- setup.py
> Fixed tester scripts

- scripts/tracker_plugin.py
> Fixed set size change in tracker

- ipv8/attestation/trustchain/community.py
- scripts/trustchain_crawler_plugin.py
- systemd/trustchain-crawler.service
Added a TrustChainCrawler community, that crawls a random discovered peer every two second. Also added support to crawl blocks in the pre-7.3 TrustChain communities. I also fixed the systemd file.
> Improved TrustChain crawler

- ipv8/REST/dht_endpoint.py
- ipv8/REST/noblock_dht_endpoint.py
- ipv8/REST/trustchain_endpoint.py
- ipv8/REST/tunnel_endpoint.py
- ipv8/attestation/trustchain/community.py
- ipv8/requestcache.py
- ipv8/test/REST/dht/test_dht_endpoint.py
- ipv8/test/REST/rest_base.py
- ipv8_service.py
Fixes https://github.com/Tribler/py-ipv8/issues/625, possibly fixes https://github.com/Tribler/py-ipv8/issues/676.
> Fixed Trustchain issue due to asyncio porting

- ipv8/lazy_community.py
> Added ez_send shortcut

- README.md
> Fixed possible README PyPi issues

- ipv8_service.py
Most notably this causes `Test_BootstrapServers` to fail.
> Fixed thread hog when no strategies are running

- ipv8/messaging/interfaces/udp/endpoint.py
Partially reinstates the old socket code to detect reuse of ports.
> Fixed reuse of ports not being detected

- ipv8/lazy_community.py
> Updated lazy_community docstrings

- ipv8/messaging/deprecated/encoding.py
- ipv8/test/REST/attestationendpoint/test_attestation_endpoint.py
> Fixed binary data in TC tx err 500

- ipv8/messaging/anonymization/tunnel.py
> Fixed uncaught socket aton

- ipv8/dht/community.py
Fixes https://github.com/Tribler/py-ipv8/issues/721.
> Fix token error if message arrives before DHT is initialized

- ipv8/messaging/anonymization/tunnel.py
> Catch resolve tunnel error

- ipv8/dht/discovery.py
- ipv8/dht/routing.py
- ipv8/dht/storage.py
- ipv8/dht/trie.py
- ipv8/messaging/anonymization/hidden_services.py
- ipv8/peerdiscovery/churn.py
- ipv8/peerdiscovery/discovery.py
- ipv8/requestcache.py
> Remove use of 'del' where possible

- doc/basics/attestation_tutorial.rst
The 10 second timeout was fixed months ago.
> Fixed attestation tutorial documentation

- setup.py
Suggested release message
---
Tag version: 2.1
Release title: IPv8 v2.1.1325 release
Body:
Includes the first 1325 commits (+158 since v2.0) for IPv8, containing:
- Replace twisted with asyncio
- Eliminated use of random.randint for IRMA
- Added swagger docs
- READY: Simplify REST tests
- Fix delayed/missing stacktraces
- Added option to TaskManager for ignoring certain Exceptions
- Added VariablePayload compilation decorator
- Docs IPv8 features, Why does IPv8 exist?
- Fix url for getting trustchain blocks for a specific user
- Fix issue with hidden services tests
- Make TunnelCrypto compatible with libnacl 1.7
- Small usability improvements for registering anonymous tasks
- Fixed trustchain crawler lambda
- Unite system path modifications as __scriptpath__.py files
- Fixed bootstrap …
> Automated Version Update

- github_increment_version.py
> Fixed automated GitHub PR script

- ipv8/attestation/tokenchain/chain.py
- ipv8/attestation/tokenchain/token.py
- ipv8/test/attestation/tokenchain/test_chain.py
- ipv8/test/attestation/tokenchain/test_token.py
- test_classes_list.txt
This is the first part of #733, adding chains of tokens devoid of metadata.
All code is typed and documented.
To guide reviews, this is the visualization of the datastructure:
Some of the guarantees and design principles:
- A "view" of a (partial) TokenChain can be (re)constructed and verified without knowledge of the public key or the contents.
- The signatures and the genesis block pointer can be verified with a public key (not part of the public serialized "view").
- Given a token and content, it can be shown whether the content belongs to the token. Given the token, it cannot be derived what content belongs to it (hash).
- The serialization can take any key format with a known signature length. The serialization is bound to 32-byte/256-bit hashes.
In future work, the content will be …
> Added token chaining datastructure

- create_test_coverage_report.py
> Fix coverage report not registering module-import coverage

- run_all_tests.py
Fixes #761
This is now correctly failing.
> Fixed test runner ignoring failures.

- ipv8/test/dht/test_discovery.py
> Fixed DHT ping assert location

- ipv8/attestation/trustchain/database.py
- ipv8/test/attestation/trustchain/test_database.py
Also written a unit test that uses a real TC database.
Fixes #764
> Fixed Trustchain update script

- ipv8/REST/asyncio_endpoint.py
- ipv8/REST/root_endpoint.py
- ipv8/taskmanager.py
This PR:
* Renames HealthEndpoint to AsyncioEndpoint
* Adds task and debug endpoints
* Fixes an issue with drift measurements not disabling when asked
> Added Asyncio debug endpoints

- run_all_tests.py
- setup.py
> Small fixes

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
This PR adds support for three issue templates:
- Bug reports.
- Feature requests.
- Questions.
My apologies for creating a branch on the main repo, the GitHub interface didn't really allow for anything else.
> Added issue templates

- doc/basics/identity_tutorial.rst
- doc/further-reading/advanced_identity.rst
- ipv8/REST/identity_endpoint.py
- ipv8/attestation/communication_manager.py
- ipv8/attestation/identity/community.py
Fixes #796
This PR:
- Adds a rendezvous token to limit exposure of pseudonyms.
- Adds documentation on the advanced (real-world) use of the identity REST API.
> Add advanced attestation tutorial

- ipv8/messaging/anonymization/caches.py
- ipv8/messaging/anonymization/community.py
- ipv8/messaging/anonymization/endpoint.py
- ipv8/messaging/anonymization/hidden_services.py
- ipv8/messaging/anonymization/payload.py
- ipv8/messaging/anonymization/tunnel.py
- ipv8/messaging/anonymization/tunnelcrypto.py
- ipv8/test/messaging/anonymization/test_community.py
- ipv8/test/messaging/anonymization/test_hiddenservices.py
Fixes https://github.com/Tribler/py-ipv8/issues/803.
> Fix for encoding hostnames in TunnelCommunity

- ipv8/REST/overlays_endpoint.py
Fixes https://github.com/Tribler/py-ipv8/issues/805.
> Fixed issue with missing public keys in OverlaysEndpoint

- ipv8/attestation/communication_manager.py
Fixes https://github.com/Tribler/tribler/issues/5450
> Don't load database on CommunicationManager start

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
This PR:
- Adds a default Pull Request template.
> Added a Pull Request template

- README.md
Fixes #778
This PR:
- Adds the daily mutation tester output badge to the README file.
> Added mutation test badge to README

- ipv8/messaging/anonymization/community.py
The log statement that I removed is clogging the Tribler logs and is uninformative in general.
> Removed log statement

- README.md
This PR:
- Updates the "Getting Started" section in the `README.md` to be less cluttered.
> Simplified Getting Started in README.md

- ipv8/test/REST/test_attestation_endpoint.py
- ipv8/test/REST/test_identity_endpoint.py
- ipv8/test/REST/test_network_endpoint.py
This PR:
- Adds tests for the REST API's `NetworkEndpoint`.
- Updates the paths of the `IdentityEndpoint` and `AttestationEndpoint` to not be the only files in a subdirectory.
> Added NetworkEndpoint REST API tests

- ipv8/peer.py
- ipv8/peerdiscovery/network.py
Related to #615
This PR:
- Adds support for multiple addresses per `Peer` in the `Peer` and `Network` classes.
This is backwards compatible with the old style of using `.address`.
> Added multiple Peer interfaces support

- ipv8/test/REST/rest_base.py
Also fixed a typo (directionary -> dictionary) and added missing docstrings.
> Added HTTP status code verification to make_request

- ipv8/messaging/interfaces/dispatcher/endpoint.py
This PR:
- Adds `bytes_up` and `bytes_down` to the `DispatcherEndpoint`
> Added bytes_up and bytes_down to DispatcherEndpoint

- ipv8/peer.py
- ipv8/test/test_peer.py
Related to #615
This PR:
- Adds `DirtyDict`, a dictionary subclass that sets a `dirty` flag when it is modified.
- Updates `Peer.address` to no longer be deprecated.
- Updates `Peer.address` to be restricted to tuples of `(str, int)`.
- Updates `Peer.addresses` to be read-only for performance of `Peer.address`.
This implementation focuses on speed instead of maintainability as `.address` is called very often.
> Undeprecated Peer.address

- ipv8/attestation/trustchain/caches.py
- ipv8/attestation/wallet/community.py
- ipv8/attestation/wallet/primitives/attestation.py
- ipv8/community.py
- ipv8/dht/community.py
- ipv8/keyvault/public/m2crypto.py
- ipv8/messaging/anonymization/community.py
- ipv8/messaging/deprecated/encoding.py
- ipv8/messaging/interfaces/statistics_endpoint.py
- ipv8/test/keyvault/test_crypto.py
Fixes https://github.com/Tribler/py-ipv8/issues/841.
> Removed unnecessary ord calls

- ipv8/loader.py
Related to https://github.com/Tribler/tribler/pull/5597
This PR:
- Adds alternative Community loading constructs from Gumby.
> Added CommunityLauncher (from Gumby)

- create_test_coverage_report.py
Fixes #861
This PR:
- Adds generation of `coverage/plotbars.R` in `create_test_coverage_report.py`.
- Fixes a line-too-long error in `create_test_coverage_report.py`.
- Updates `create_test_coverage_report.py` to no longer ignore `ipv8/keyvault/libnacl/*` (which does not exist anymore).
This is the output of the generated R script:
> Added coverage barplot script generation

- doc/basics/identity_tutorial_integration/__init__.py
- doc/basics/identity_tutorial_integration/attestation_tutorial_attest.py
- doc/basics/identity_tutorial_integration/attestation_tutorial_common.py
- doc/basics/identity_tutorial_integration/attestation_tutorial_verify.py
- doc/basics/identity_tutorial_integration/main.py
- doc/deprecated/attestation_tutorial_integration/__init__.py
- doc/deprecated/attestation_tutorial_integration/attestation_tutorial_attest.py
- doc/deprecated/attestation_tutorial_integration/attestation_tutorial_common.py
- doc/deprecated/attestation_tutorial_integration/attestation_tutorial_verify.py
- doc/deprecated/attestation_tutorial_integration/main.py
(Finally) fixes #872
This PR:
- Adds my secret integration test scripts for both the deprecated and current identity REST API.
> Added identity integration test scripts

- doc/basics/identity_tutorial_integration/attestation_tutorial_common.py
- doc/deprecated/attestation_tutorial_integration/attestation_tutorial_common.py
- doc/deprecated/attestation_tutorial_integration/main.py
Fixes #896
This PR:
- Adds a rendezvous token to the new identity integration test.
- Adds a community isolation to the deprecated identity integration test.
> Added identity integration test isolation

- ipv8/test/REST/test_attestation_endpoint.py
- ipv8/test/REST/test_identity_endpoint.py
- ipv8/test/REST/test_network_endpoint.py
- ipv8/test/attestation/identity/test_identity.py
- ipv8/test/attestation/trustchain/test_community.py
- ipv8/test/attestation/wallet/test_attestation_community.py
- ipv8/test/base.py
- ipv8/test/dht/test_churn.py
- ipv8/test/dht/test_community.py
- ipv8/test/dht/test_discovery.py
- ipv8/test/messaging/anonymization/test_community.py
- ipv8/test/messaging/anonymization/test_hiddenservices.py
Fixes #897
This PR:
- Adds shortcuts for common node attributes in `TestBase`.
- Updates unit tests to use the new shortcuts.
> Added TestBase shortcuts

- ipv8/test/base.py
Related to https://github.com/Tribler/tribler/issues/5683
This PR:
- Adds fragile packet handling in `TestBase`.
- Updates `TestBase` to set itself as the `asyncio` exception handler.
Notable caveats:
- With the way `asyncio` works, we can only sweep up errors after a test run has completed. This means that compound errors may cause the root of the issue to be shadowed. For example the situation `message handler has exception and fails to execute some code -> class invariant is violated elsewhere -> exception` would seem like a case of `class invariant is violated elsewhere -> exception` instead of `message handler has exception`. Chronologically speaking: the last exception would be triggered first.
- Any node `i` inserted after `initialize()` will need to have `patch_overlays(i)` called …
> Made packet handling fragile in TestBase

- ipv8/community.py
This PR:
- Adds automatic address type hinting for bootstrap nodes.
- Fixes `tuple` addresses not being allowed to match to old style introduction requests, even if they contain IPv4 addresses.
- Fixes deferred appending to `_DEFAULT_ADDRESSES` (through DNS resolution) not appearing in the Network blacklist.
Small implementation gotcha: `UDP*Address` instances are sublclasses of `tuple`.
> Fixed overzealous defensive programming in create_introduction_request

- scripts/tracker_plugin.py
Fixes #921
This PR:
- Fixes the tracker script Community not listening to all packets.
> Fixed tracker script not being general listener

- ipv8/peerdiscovery/network.py
- ipv8/test/peerdiscovery/test_network.py
Fixes #928
This PR:
- Updates Network.snapshot to capture all kind of addresses (instead of only IPv4).
> Added Network.snapshot support for all addresses

- ipv8/REST/isolation_endpoint.py
- ipv8/bootstrapping/bootstrapper_interface.py
- ipv8/bootstrapping/dispersy/bootstrapper.py
- ipv8/community.py
- ipv8/configuration.py
- ipv8/dht/community.py
- ipv8/loader.py
- ipv8/test/REST/test_identity_endpoint.py
- ipv8/test/REST/test_isolation_endpoint.py
- ipv8/test/bootstrapping/dispersy/test_bootstrapper.py
- ipv8/test/peerdiscovery/test_churn.py
- ipv8/test/peerdiscovery/test_community.py
- ipv8/test/peerdiscovery/test_edge_discovery.py
- ipv8/test/peerdiscovery/test_random_discovery.py
- ipv8/test/test_configuration.py
- ipv8/test/test_loader.py
- ipv8_service.py
- stresstest/bootstrap_rtt.py
Fixes #946
This PR:
- Adds a `Bootstrapper` interface for generic bootstrapping.
- Adds a `DispersyBootstrapper` implementation for the default IPv8 bootstrapping.
- Adds bootstrapping configuration options to the overlay configuration entries.
- Adds a `bootstrapper` definition for `loader.py` loading.
- Removes hard-coded bootstrapping logic from `Community`.
Notable changes:
- To inspect the IPv8 bootstrap ips use `DISPERSY_BOOTSTRAPPER['init']['ip_addresses']` instead of `_DEFAULT_ADDRESSES`.
- `Community` instances start without any bootstrapping implementation, cleaning up many tests, Tribler and Gumby.
This PR requires changes in Tribler and Gumby (I'll take care of these).
> Modularized Community bootstrapping

- doc/basics/requestcache_tutorial.rst
- doc/basics/requestcache_tutorial_1.py
- doc/basics/requestcache_tutorial_2.py
- doc/basics/requestcache_tutorial_3.py
Fixes #951
This PR:
- Adds documentation on the very basics of `RequestCache` use.
> Added RequestCache documentation

- ipv8/REST/overlays_endpoint.py
- ipv8/REST/schema.py
- ipv8/REST/tunnel_endpoint.py
- ipv8/community.py
- ipv8/dht/community.py
- ipv8/loader.py
- ipv8/messaging/anonymization/caches.py
- ipv8/messaging/anonymization/community.py
- ipv8/messaging/anonymization/hidden_services.py
- ipv8/messaging/anonymization/pex.py
- ipv8/messaging/anonymization/tunnel.py
- ipv8/messaging/anonymization/utils.py
- ipv8/test/test_loader.py
This PR fixes various issues with the `PexCommunity` and peer discovery in general. Also, it contains several tweaks that should increase the success rate of creating end-to-end circuits. And finally, I added some additional debug information to the tunnels and overlays endpoints.
> Update hidden services peer discovery

- ipv8/messaging/anonymization/hidden_services.py
- ipv8/messaging/anonymization/tunnel.py
Fixes https://github.com/Tribler/py-ipv8/issues/984.
> Fix compatibility with Python 3.8

- doc/basics/testbase_tutorial.rst
- doc/basics/testbase_tutorial_1.py
Fixes #983
This PR:
- Adds documentation for `TestBase`.
> Added TestBase tutorial

- doc/index.rst
- doc/simulation/simulation_tutorial.rst
- doc/simulation/simulation_tutorial_1.py
- simulation/discrete_loop.py
- simulation/simulation_endpoint.py
This PR:
- Adds basic simulation functionality to IPv8, including documentation and a code snippet on how to use this functionality.
> Added basic simulation capabilities to IPv8

- ipv8/test/mocking/ipv8.py
This PR:
- Adds support for supplying a custom `Peer` as the `my_peer` of `MockIPv8`.
- Fixes `MockIPv8` taking variable args after keyword args.
> Allow custom my_peer instead of key curve in MockIPv8

- doc/index.rst
- doc/reference/community_best_practices.rst
Fixes #1022
This PR:
- Adds documentation for Community best practices.
> Added best practices documentation

- doc/basics/overlay_tutorial_5.py
Fixes #1055
This PR:
- Updates `doc/basics/overlay_tutorial_5.py` to use dataclass payloads instead of `VariablePayload`.
> Updated overlay tutorial to use dataclass payloads

- ipv8/bootstrapping/dispersy/bootstrapper.py
Fixes https://github.com/Tribler/py-ipv8/issues/1081
This PR:
- Adds a single line that imports idna encoding which prevents Lookup Error on unicode hostname resolution
> Fixed idna Lookup Error

- ipv8/test/test_requestcache.py
Fixes #1089
This PR:
* Fixes the shutdown of the `RequestCache` instance in multiple tests of `test_requestcache.py`
> Fixed shutdown of RequestCache in tests

- ipv8/messaging/anonymization/caches.py
- ipv8/messaging/anonymization/community.py
- ipv8/test/messaging/anonymization/test_community.py
Fixes #1044
This PR:
- Updates packet handling in the TunnelCommunity tests to be fragile (just like `TestBase` does for non-anonymized packets).
- Updates `TunnelCommunity.remove_circuit()` to immediately remove associated `RetryRequestCache` instances.
- Updates `RetryRequestCache` to be coupled to a circuit id instead of a random id (packet identifiers are still random shorts).
- Updates usage of `RetryRequestCache` to log explicitly where and how they are replaced or removed.
Notes:
- Instead of `RetryRequestCache` instances being able to freely exist alongside each other, this PR now forces existing instances to be canceled whenever a new instance is created.
- The fragile packet handling code was copied verbatim from [#1044](https://github.com/Tribler/py-ipv8/issues/1044#issuecomment …
> Updated retry cache for circuits

- ipv8/bootstrapping/udpbroadcast/bootstrapper.py
Fixes #1076
This PR:
- Adds a bootstrap timeout for the `UDPBroadcastBootstrapper`.
This code has been copied from the [`DispersyBootstrapper` implementation](https://github.com/Tribler/py-ipv8/blob/master/ipv8/bootstrapping/dispersy/bootstrapper.py).
> Added UDP broadcast bootstrap timeout

- README.md
Fixes #1104
This PR:
- Updates the README to say the project is based on research from the last 18 years.
> Updated project age in README

- doc/further-reading/advanced_peer_discovery.rst
- doc/index.rst
Fixes #979
This PR:
- Adds documentation for different DiscoveryStrategies.
> Added advanced discovery docs

- run_all_tests.py
Fixes #1120
This PR:
- Adds ANSI code support for Windows in the test runner output.
- Fixes two Flake8 `F541: f-string is missing placeholder` instances.
- Updates the test runner to cap out at 60 test processes, to avoid running out of handles.
> Updated Windows test runner script

- ipv8/attestation/communication_manager.py
- ipv8/attestation/identity/community.py
- ipv8/community.py
- ipv8/messaging/lazy_payload.py
- ipv8/messaging/payload_dataclass.py
- ipv8/messaging/serialization.py
- ipv8/peerdiscovery/network.py
- ipv8/requestcache.py
Fixes #1134
This PR:
- Fixes the MyPy issues exposed by the most recent MyPy version.
> Fixed MyPy issues after upgrade

- run_all_tests.py
Fixes #1137
This PR:
- Updates `run_all_tests.py` to use `concurrent.futures.ProcessPoolExecutor.map` instead of `multiprocessing.Pool.starmap_async`. This new implementation handles segfaults.
- Updates `run_all_tests.programmer_distractor` function to run as a `contextlib.AbstractContextManager`. The old function was broken due to the switch to `ProcessPoolExecutor.map`.
- Removes the `run_all_tests.make_buckets` function. This functionality is now handled by `ProcessPoolExecutor`.
All 8 scenarios with the flags `-q`, `-a` and a segfaulting test (or not) have been manually tested:
With segfaulting test:
```
>python run_all_tests.py
Launching in 60 processes ... awaiting results ... test suite process crash! Segfault?
====================================================================== …
```
> Handle segfaults in `run_all_tests.py`

- ipv8/peerdiscovery/network.py
- ipv8/test/peerdiscovery/test_network.py
Fixes #1145
This PR:
- Adds an observer pattern to `Network` (using the `PeerObserver` interface) that is notified upon peer addition or removal.
Note:
- The notification happens inside of the graph lock to disallow observers causing more notifications while being notified.
> Added Network PeerObservers

- ipv8/test/attestation/wallet/test_attestation_community.py
Related to #1157
This PR:
- Updates `test_load_key` to use a mocked database response instead of reloading the database from an actual file.
> Updated `test_load_key` to not use a real db file

- ipv8/attestation/communication_manager.py
- ipv8/test/REST/test_identity_endpoint.py
Fixes #1157
This PR:
- Updates `CommunicationManager` to use a `PseudonymFolderManager` to perform all file I/O.
- Updates `TestIdentityEndpoint` to use a dictionary instead of a real folder structure.
> Updated `TestIdentityEndpoint` to not use real files

- ipv8/REST/dht_endpoint.py
- ipv8/dht/__init__.py
- ipv8/dht/churn.py
- ipv8/dht/community.py
- ipv8/dht/discovery.py
- ipv8/dht/payload.py
- ipv8/dht/provider.py
- ipv8/dht/routing.py
- ipv8/dht/storage.py
- ipv8/dht/trie.py
- ipv8/test/dht/test_trie.py
- ipv8/types.py
This PR:
- Fixes the `ruff` violations in the `dht` folder.
> Fixed ruff violations for dht folder

- ipv8/REST/overlays_endpoint.py
- ipv8/attestation/communication_manager.py
- ipv8/messaging/interfaces/dispatcher/endpoint.py
- ipv8/messaging/interfaces/endpoint.py
- ipv8/messaging/interfaces/lan_addresses/addressprovider.py
- ipv8/messaging/interfaces/lan_addresses/any_os/getaddrinfo.py
- ipv8/messaging/interfaces/lan_addresses/any_os/netifaces.py
- ipv8/messaging/interfaces/lan_addresses/any_os/testnet1.py
- ipv8/messaging/interfaces/lan_addresses/importshield.py
- ipv8/messaging/interfaces/lan_addresses/interfaces.py
- ipv8/messaging/interfaces/lan_addresses/unix/getifaddrs.py
- ipv8/messaging/interfaces/lan_addresses/unix/ioctl.py
- ipv8/messaging/interfaces/lan_addresses/windows/GetAdaptersAddresses.py
- ipv8/messaging/interfaces/network_stats.py
- ipv8/messaging/interfaces/statistics_endpoint.py
- ipv8/messaging/interfaces/udp/endpoint.py
- ipv8/test/messaging/interfaces/dispatcher/test_endpoint.py
This PR:
- Fixes the `ruff` violations in the `messaging/interfaces` folder.
> Fixed ruff violations for messaging interfaces folder

- ipv8/REST/tunnel_endpoint.py
- ipv8/dht/payload.py
- ipv8/messaging/anonymization/caches.py
- ipv8/messaging/anonymization/community.py
- ipv8/messaging/anonymization/endpoint.py
- ipv8/messaging/anonymization/hidden_services.py
- ipv8/messaging/anonymization/payload.py
- ipv8/messaging/anonymization/pex.py
- ipv8/messaging/anonymization/tunnel.py
- ipv8/messaging/anonymization/tunnelcrypto.py
- ipv8/messaging/anonymization/utils.py
- ipv8/messaging/lazy_payload.py
This PR:
- Fixes the `ruff` violations in the `messaging/anonymization` folder.
> Fixed ruff violations for messaging anonymization folder

- ipv8/messaging/payload.py
- ipv8/messaging/payload_headers.py
- ipv8/peerdiscovery/payload.py
This PR:
- Fixes the remaining `ruff` violations in the `messaging` folder.
> Fixed ruff violations for messaging top folder 

- ipv8/REST/dht_endpoint.py
- ipv8/REST/overlays_endpoint.py
- ipv8/REST/tunnel_endpoint.py
- ipv8/attestation/identity/community.py
- ipv8/attestation/identity/database.py
- ipv8/community.py
- ipv8/configuration.py
- ipv8/database.py
- ipv8/dht/community.py
- ipv8/lazy_community.py
- ipv8/loader.py
- ipv8/messaging/anonymization/caches.py
- ipv8/messaging/anonymization/community.py
- ipv8/messaging/anonymization/hidden_services.py
- ipv8/messaging/anonymization/payload.py
- ipv8/messaging/anonymization/pex.py
- ipv8/messaging/anonymization/tunnel.py
- ipv8/messaging/anonymization/tunnelcrypto.py
- ipv8/messaging/payload.py
- ipv8/messaging/payload_headers.py
- ipv8/messaging/serialization.py
- ipv8/overlay.py
- ipv8/peerdiscovery/churn.py
- ipv8/peerdiscovery/community.py
- ipv8/requestcache.py
- ipv8/taskmanager.py
- ipv8/test/base.py
- ipv8/types.py
- ipv8/util.py
This PR:
- Fixes the remaining ruff violations in the top folder.
- Removes `AnyPayload` and `AnyPayloadType` as these are no longer necessary.
This PR finally pulls all preceding PRs together 🎉, making typing usable/useful within IPv8.
> Fixed ruff violations for the top-level folder

- create_test_coverage_report.py
- github_increment_version.py
- ipv8/messaging/interfaces/lan_addresses/unix/getifaddrs.py
- ipv8/test/base.py
- ipv8_service.py
- run_all_tests.py
This PR:
- Fixes `ruff` issues in `create_test_coverage_report.py`, `github_increment_version.py`, and `run_all_tests.py`.
Secondarily, updates other files due to upstream `ruff` rule updates.
> Fixed ruff violations beyond top folder

- ipv8/dht/community.py
- ipv8/dht/provider.py
Related to #1175
This PR:
- Updates the DHT `community.py` to use a `DHTValue` type to decrease the type (visual) complexity.
> Updated dht community to use DHTValue type

- ipv8/peerdiscovery/payload.py
This PR updates the `DiscoveryCommunity` payloads to use `ipv4` instead of `4SH` for serializing IP addresses.
The rest of the codebase has already moved to the newer notation.
> Updated DiscoveryCommunity payloads to use ipv4 instead of 4SH

- doc/validate_examples.py
Fixes #1202
This PR:
- Fixes `validate_examples.py` not running documentation scripts as `__main__` modules.
> Fixed doc validation not running as __main__

- doc/reference/community_best_practices.rst
Fixes #1213
This PR:
- Updates the best practices tutorial to use the new `CommunitySettings`.
> Updated best practices code to fit CommunitySettings

- .github/workflows/pr-comment-validate.yml
Related to #1056
This PR:
- Adds a dummy workflow file that *should* trigger on a PR comment.
The next PR will be used to test this action.
> Added dummy workflow file for extended validation tests

- .github/workflows/pr-comment-validate.yml
Fixes #1056
This PR:
- Updates the validation GitHub action to run the unit tests.
> Updated validate action to run the unit tests

- README.md
- run_all_tests.py
This PR:
- Updates the project age.
The main objective of this PR is (yet again) to test the validation action matrix.
Finally, [the matrix actually works](https://github.com/Tribler/py-ipv8/actions/runs/6548876249) 🎉
> Updated the project age

- ipv8/lazy_community.py
Fixes https://github.com/Tribler/py-ipv8/issues/1232.
> Fixed peer addresses not being updated

- ipv8/taskmanager.py
- ipv8/test/test_taskmanager.py
This PR does the following:
* Adds support for `Futures` to the `TaskManager`
* Adds `TaskManager.register_executor_task` that allows for non-async functions to be scheduled on the threadpool. It's important to note while `TasksManager.shutdown` will cancel the future itself, it won't actually stop the task (unless you manually add support for this, for example, by passing an event).
> Added support for Futures to the TaskManager

- ipv8/dht/community.py
- ipv8/messaging/anonymization/hidden_services.py
- ipv8/messaging/anonymization/tunnel.py
This PR fixes https://github.com/Tribler/py-ipv8/issues/1262.
> Fixed typing issues

- ipv8/messaging/anonymization/community.py
- ipv8/messaging/anonymization/hidden_services.py
- ipv8/test/messaging/anonymization/test_hiddenservices.py
This PR stops hidden services removing data circuits, as it may conflict with circuit management in Tribler.
> Updated hidden services to stop removing data circuits

- .github/workflows/mypy.yml
- .github/workflows/ruff.yml
- .github/workflows/unittests.yml
This PR partially addresses https://github.com/Tribler/py-ipv8/issues/1279 by adding workflows for ruff/mypy/unittests.
> Added ruff/mypy/unittest workflows

- .github/workflows/pr-comment-validate.yml
- .github/workflows/unittests.yml
- .ruff.toml
Partially addresses https://github.com/Tribler/py-ipv8/issues/1279 by porting the remaining validation tests to GitHub Actions.
Also fixes https://github.com/Tribler/py-ipv8/issues/1282.
> Added validation tests to GitHub Actions

- .github/workflows/pr-comment-validate.yml
- ipv8/test/dht/test_community.py
Fixes https://github.com/Tribler/py-ipv8/issues/1287.
> Fix pending task error in test_unload_while_contacting_node

- ipv8/taskmanager.py
- ipv8/test/test_taskmanager.py
Fixes #1275
This PR:
- Adds `TaskManager.get_task()` to retrieve a named task.
- Adds `TaskManager.get_anonymous_tasks()` to retrieve anonymous tasks.
- Updates `taskmanager.py` to use double quotes.
- Updates `test_taskmanager.py` to use double quotes.
> Added methods for task retrieval to `TaskManager`

- doc/further-reading/anonymization.rst
Fixes #1313
This PR:
- Updates the `TunnelCommunity` documentation to be up-to-date with modern Python and our implementation.
> Updated TunnelCommunity docs

- .github/workflows/weekly_mutation_tests.yml
Fixes #1279
This PR:
- Adds a weekly mutation test workflow.
This is a port of https://github.com/Tribler/tribler/pull/8238
> Hook in weekly mutation test

- ipv8/REST/tunnel_endpoint.py
Recently, we've released a new version of the Rust endpoint that has its own speed test logic built-in. This PR modifies the `TunnelEndpoint` to start using this functionality.
In order for the test in Rust to work properly I had to change the identifiers in the test-request/response messages from 16-bit to 32-bit. Since the tests now work differently in Rust, I've disabled the Python version.
> Updated TunnelEndpoint to test circuits in Rust
